stages:
  - build
  - test
  - publish

variables:
  FF_GITLAB_REGISTRY_HELPER_IMAGE: 1
  FF_USE_FASTZIP: "true" # enable fastzip - a faster zip implementation that also supports level configuration.
  ARTIFACT_COMPRESSION_LEVEL: default # can also be set to fastest, fast, slow and slowest. If just enabling fastzip is not enough try setting this to fastest or fast.
  CACHE_COMPRESSION_LEVEL: default # same as above, but for caches
  TRANSFER_METER_FREQUENCY: 5s # will display transfer progress every 5 seconds for artifacts and remote caches


build:
  stage: build
  image: $HARBOR_URL/proxy_cache/library/node:latest
  script:
    - echo "Start building App"
    - npm config set proxy http://tkgeproxy1.statkart.no:3128
    - npm config set https-proxy http://tkgeproxy1.statkart.no:3128
    - npm install
    - npm run build
    - ls -la
    - export VERSION=$(node -p "require('./package.json').version")
    - echo "${VERSION}.${CI_JOB_ID}"
    - echo "PROJECT_VERSION=${VERSION}.${CI_JOB_ID}" > build.env
    #bruk build-jobbens unike id som utgangspunkt for patch-delen av semver-versjonstagg
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/
    reports:
      dotenv: build.env

test:
  stage: test
  image: $HARBOR_URL/proxy_cache/library/node:latest
  script:
    - echo "Testing App, placeholder"
    #    - CI=true npm test
    - echo "Test successfully!"

publish:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - |-
      KANIKOPROXYBUILDARGS=""
      KANIKOCFG="{ \"auths\":{\"$HARBOR_URL\":{\"username\":\"$HARBOR_USERNAME\",\"password\":\"$HARBOR_TOKEN\"}}"
      if [ "x${http_proxy}" != "x" -o "x${https_proxy}" != "x" ]; then
        KANIKOCFG="${KANIKOCFG}, \"proxies\": { \"default\": { \"httpProxy\": \"${http_proxy}\", \"httpsProxy\": \"${https_proxy}\", \"noProxy\": \"${no_proxy}\"}}"
        KANIKOPROXYBUILDARGS="--build-arg http_proxy=${http_proxy} --build-arg https_proxy=${https_proxy} --build-arg no_proxy=${no_proxy}"
      fi
      KANIKOCFG="${KANIKOCFG} }"
      echo "${KANIKOCFG}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile-ci $KANIKOPROXYBUILDARGS --destination $HARBOR_URL/nibas/nibas-klient-frontend:${PROJECT_VERSION}
  only:
    refs:
      - master
  except:
    - tags
  dependencies:
    - build
