# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "nibas-frontend"
  tags:
  - "internal"
spec:
  type: "website"
  lifecycle: "production"
  owner: "smia"
  system: "nibas"
