FROM caddy:2.8.1-alpine

COPY /build /srv

ENV PORT=8082
ENV BACKEND_HOST=localhost:8080
RUN apk --no-cache add curl tzdata
RUN addgroup -g 1242 nibas; \
  adduser -u 1242 -D -G nibas nibas
COPY build-config/caddy/Caddyfile /etc/caddy/Caddyfile
ENV TZ=Europe/Oslo
USER 1242
EXPOSE 8080
