FROM node:lts as nodeContainer
WORKDIR /app
COPY . .
RUN npm install
RUN rm -f .npmrc
RUN npm run build

FROM caddy:2.7-alpine
ENV PORT=8080
ENV BACKEND_HOST=nibas-backend
RUN apk --no-cache add tzdata
RUN addgroup -g 1242 nibas; \
  adduser -u 1242 -D -G nibas nibas
COPY build-config/caddy/Caddyfile /etc/caddy/Caddyfile
COPY --from=nodeContainer /app/build/ /srv
ENV TZ=Europe/Oslo
USER 1242
