FROM node:lts as nodeContainer
WORKDIR /app
COPY . .
RUN npm install
RUN rm -f .npmrc
RUN npm run build

FROM caddy:2-alpine
RUN addgroup -g 1242 nibas; \
  adduser -u 1242 -D -G nibas nibas
COPY build-config/caddy/Caddyfile-local /etc/caddy/Caddyfile
COPY --from=nodeContainer /app/build/ /srv
USER 1242
