/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/nasjoner/{id}": {
    /** Henter nasjon med gitt id */
    get: operations["hentEn"];
    put: operations["oppdaterNasjon"];
  };
  "/v1/kommuner/{id}": {
    /** Henter kommune med gitt id */
    get: operations["hentEn_1"];
    /** Oppdaterer angitt kommune. Returnerer den oppdaterte kommunen */
    put: operations["oppdaterKommune"];
  };
  "/v1/fylker/{id}": {
    /** Henter fylke med gitt id */
    get: operations["hentEn_2"];
    put: operations["oppdaterFylke"];
  };
  "/v1/admin/kodelister/invalidate": {
    /** Invaliderer kodeliste-cache slik at kodelister refreshes. */
    put: operations["invalidateKodelisteCache"];
  };
  "/v1/import": {
    post: operations["importer"];
  };
  "/v1/grenser": {
    post: operations["lagreGrenser"];
  };
  "/v1/nasjoner": {
    /** Henter alle nasjoner i nasjonal inndelingsbase. */
    get: operations["hentAlle"];
  };
  "/v1/nasjoner/{id}/historikk": {
    /** Henter historikken til en nasjon med gitt id */
    get: operations["hentHistorikkForEn"];
  };
  "/v1/nasjoner/{id}/historikk/{revision}": {
    /** Henter en gitt revisjon av en historisk nasjon */
    get: operations["hentHistorikkRevisjon"];
  };
  "/v1/nasjoner/{id}/grenser": {
    /** Henter grensene til en nasjon med gitt id */
    get: operations["hentGrenser"];
  };
  "/v1/kommuner": {
    /** Henter alle kommuner i nasjonal inndelingsbase. */
    get: operations["hentAlle_1"];
  };
  "/v1/kommuner/{id}/historikk": {
    /** Henter historikken til en kommune med gitt id */
    get: operations["hentHistorikkForEn_1"];
  };
  "/v1/kommuner/{id}/historikk/{revision}": {
    /** Henter en gitt revisjon av en historisk kommune */
    get: operations["hentHistorikkRevisjon_1"];
  };
  "/v1/kommuner/{id}/grenser": {
    /** Henter grensene til en kommune med gitt id */
    get: operations["hentGrenser_1"];
  };
  "/v1/kodeliste/maalemetode-koder": {
    get: operations["fetchMaalemetodeKoder"];
  };
  "/v1/kodeliste/kommunenumre": {
    get: operations["fetchKommunenumre"];
  };
  "/v1/kodeliste/fylkesnumre": {
    get: operations["fetchFylkesnumre"];
  };
  "/v1/grenser/territorialgrenser/{id}": {
    /** Henter territorialgrense med gitt id */
    get: operations["hentTerritorialsgrense"];
  };
  "/v1/grenser/territorialgrenser/{id}/historikk": {
    /** Henter historikk for territorialgrense med gitt id */
    get: operations["hentTerritorialgrenseHistorikk"];
  };
  "/v1/grenser/territorialgrenser/{id}/historikk/{revision}": {
    /** Henter gitt revisjon for gitt territorialgrense */
    get: operations["hentTerritorialgrenseRevisjon"];
  };
  "/v1/grenser/riksgrenser/{id}": {
    /** Henter riksgrense med gitt id */
    get: operations["hentRiksgrense"];
  };
  "/v1/grenser/riksgrenser/{id}/historikk": {
    /** Henter historikk for riksgrense med gitt id */
    get: operations["hentRiksgrenseHistorikk"];
  };
  "/v1/grenser/riksgrenser/{id}/historikk/{revision}": {
    /** Henter gitt revisjon for gitt riksgrense */
    get: operations["hentRiksgrenseRevisjon"];
  };
  "/v1/grenser/kommunegrenser/{id}": {
    /** Henter kommunegrense med gitt id */
    get: operations["hentKommunegrense"];
  };
  "/v1/grenser/kommunegrenser/{id}/historikk": {
    /** Henter historikk for kommunegrense med gitt id */
    get: operations["hentKommunegrenseHistorikk"];
  };
  "/v1/grenser/kommunegrenser/{id}/historikk/{revision}": {
    /** Henter gitt revisjon for gitt kommunegrense */
    get: operations["hentKommunegrenseRevisjon"];
  };
  "/v1/grenser/fylkesgrenser/{id}": {
    /** Henter fylkesgrense med gitt id */
    get: operations["hentFylkesgrense"];
  };
  "/v1/grenser/fylkesgrenser/{id}/historikk": {
    /** Henter historikk for fylkesgrense med gitt id */
    get: operations["hentFylkesgrenseHistorikk"];
  };
  "/v1/grenser/fylkesgrenser/{id}/historikk/{revision}": {
    /** Henter gitt revisjon for gitt fylkesgrense */
    get: operations["hentFylkesgrenseRevisjon"];
  };
  "/v1/grenser/avtaltavgrensningslinjer/{id}": {
    /** Henter avtalt avgrensningslinje med gitt id */
    get: operations["hentAvtaltavgrensningslinje"];
  };
  "/v1/grenser/avtaltavgrensningslinjer/{id}/historikk": {
    /** Henter historikk for avtalt avgrensningslinje med gitt id */
    get: operations["hentAvtaltavgrensningslinjeHistorikk"];
  };
  "/v1/grenser/avtaltavgrensningslinjer/{id}/historikk/{revision}": {
    /** Henter gitt revisjon for gitt avtalt avgrensningslinje */
    get: operations["hentAvtaltavgrensningslinjeRevisjon"];
  };
  "/v1/fylker": {
    /** Henter alle fylker i nasjonal inndelingsbase. */
    get: operations["hentAlle_2"];
  };
  "/v1/fylker/{id}/historikk": {
    /** Henter historikken til et fylke med gitt id */
    get: operations["hentHistorikkForEn_2"];
  };
  "/v1/fylker/{id}/historikk/{revision}": {
    /** Henter en gitt revisjon av et historisk fylke */
    get: operations["hentHistorikkRevisjon_2"];
  };
  "/v1/fylker/{id}/grenser": {
    /** Henter grensene til et fylke med gitt id */
    get: operations["hentGrenser_2"];
  };
}

export interface components {
  schemas: {
    /** @description Representasjon av et navn */
    AdministrativEnhetNavn: {
      /** @description Navnet på en administrativ enhet */
      navn: string;
      /** @description Språkkoden til det administrative navnet */
      spraak: string;
    };
    NasjonRequest: {
      /** @description Navnene til nasjonen */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalId for angitt nasjon */
      lokalid: string;
      /** @description Navnerommet for nasjonen */
      navnerom: string;
    };
    /** @description Spesfikk metadata for en administrativ grense (fylkes/kommunegrense). Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Objekttype/Index/EAID_5142EDBA_4226_4ca3_924D_EECEFD216D1A */
    AdministrativGrenseMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      /** @description Opplysning om at grense følger naturlige skillelinjer i terrenget. */
      foelgerTerrengdetalj?: string;
      /** @description Klassifikasjon av stedfestingsnøyaktighet på grenser, og er basert på dårligste nøyaktighet til grensepunktene til grensen. */
      noeyaktighetsklasse?: string;
      /** @description Angir om grensen er omtvistet, eller det er tvil om forløpet. */
      omtvistet?: boolean;
    } & {
      common: unknown;
      commonGrense: unknown;
    };
    /** @description Spesifikk metadata for en AvtaltAvgrensningslinje. Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Diagram/Index/EAID_EEECEE48_B3FA_4807_AAE4_B30B63BC28E1 */
    AvtaltAvgrensningslinjeMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      maritimeGrenser?: components["schemas"]["MaritimeGrenserMetadata"];
    } & {
      common: unknown;
      commonGrense: unknown;
      maritimeGrenser: unknown;
    };
    /** @description Felles metadata-egenskaper for grenser. */
    CommonGrenseMetadata: {
      /** @description Henviser til fastsettings- eller lovinformasjon. */
      dokumentasjonsreferanser: components["schemas"]["Dokref"][];
      posisjonskvalitet?: components["schemas"]["Posisjonskvalitet"];
      /** @description Juridisk status på grensa. */
      grensestatus?: string;
      /** @description Måte en grense er fastsatt på. */
      fastsettingstype?: string;
    };
    /** @description Felles metadata-egenskaper for grenser. */
    CommonMetadata: {
      identifikasjon: components["schemas"]["Identifikasjon"];
      /**
       * Format: date-time
       * @description Dato når objektet siste gang ble registrert/observert/målt i terrenget
       */
      datafangstdato?: string;
      /**
       * Format: date-time
       * @description Tidspunktet når objektet oppstod i den virkelige verden
       */
      gyldigFra?: string;
      /**
       * Format: date-time
       * @description Tidspunktet når objektet opphørte å eksistere i den virkelige verden
       */
      gyldigTil?: string;
      /** @description Generelle opplysninger/merknad */
      informasjon?: string;
      /**
       * Format: date-time
       * @description Dato for siste endring på objektdataene
       */
      oppdateringsdato: string;
      /** @description Referanse til opphavsmaterialet, kildematerialet, organisasjons/publiseringskilde. */
      opphav?: string;
    };
    Coordinate: {
      /** Format: double */
      x?: number;
      /** Format: double */
      y?: number;
      /** Format: double */
      z?: number;
      valid?: boolean;
      coordinate?: components["schemas"]["Coordinate"];
      /** Format: double */
      m?: number;
    };
    CoordinateSequence: {
      /** Format: int32 */
      measures?: number;
      /** Format: int32 */
      dimension?: number;
    };
    CoordinateSequenceFactory: { [key: string]: unknown };
    /** @description Henviser til fastsettings- eller lovinformasjon. */
    Dokref: {
      /** @description ID for dokumentasjonsreferansen. */
      id?: string;
      /** @description URL til saksdokument. */
      dokumentlenker: components["schemas"]["TekstHolder"][];
      /**
       * Format: date
       * @description Dato for når dokumentet ble skrevet, publisert eller revidert.
       */
      fastsettingsdato: string;
      /** @description Offentlig instans som har fastsatt en grense. */
      fastsettingsmyndighet?: string;
      /** @description Lov som rettskilden er begrunnet i. */
      hjemmel?: string;
      /** @description Henvisning til saksdokument i Kartverkets eget arkiv. */
      internReferanserKartverket: components["schemas"]["TekstHolder"][];
      /** @description Referanse til lov, forskrift, vedtak, dom eller traktat i form av kode som angir type dokument, dato og nummer For eksempel: LOV-2012-09-07-65. */
      rettskildeId?: string;
      /** @description Navn på lov, forskrift, vedtak, dom eller traktat. */
      rettskildeTittel: string;
    };
    Envelope: {
      null?: boolean;
      /** Format: double */
      diameter?: number;
      /** Format: double */
      width?: number;
      /** Format: double */
      minX?: number;
      /** Format: double */
      maxX?: number;
      /** Format: double */
      minY?: number;
      /** Format: double */
      maxY?: number;
      /** Format: double */
      area?: number;
      /** Format: double */
      height?: number;
    };
    /** @description Liste av features som holder på dataene */
    Feature: {
      /** @description En konstant, navn: type, verdi: Feature */
      type: string;
      /** @description Id til feature */
      id?: string;
      properties: components["schemas"]["FeatureProperties"];
      geometry: components["schemas"]["Geometry"];
    };
    FeatureCollection: {
      /** @description Toppnivå for geojson-strukturen, definert av en konstant med navn type og verdi FeatureCollection */
      type: string;
      /** @description Liste av features som holder på dataene */
      features: components["schemas"]["Feature"][];
    };
    /** @description Egenskaper som beskriver en gitt feature (properties-objektet i geojson-strukturen) */
    FeatureProperties: {
      /** @description Definerer hvilken type geometri som leveres */
      type: string;
      metadata?: components["schemas"]["Metadata"];
      kontekstEgenskaper?: components["schemas"]["KontekstEgenskaper"];
    };
    /** @description Geometrien til denne featuren. */
    Geometry: {
      envelope?: components["schemas"]["Geometry"];
      factory?: components["schemas"]["GeometryFactory"];
      userData?: { [key: string]: unknown };
      /** Format: double */
      length?: number;
      empty?: boolean;
      valid?: boolean;
      /** Format: int32 */
      dimension?: number;
      simple?: boolean;
      /** Format: int32 */
      srid?: number;
      geometryType?: string;
      /** Format: int32 */
      numGeometries?: number;
      precisionModel?: components["schemas"]["PrecisionModel"];
      coordinate?: components["schemas"]["Coordinate"];
      coordinates?: components["schemas"]["Coordinate"][];
      /** Format: int32 */
      numPoints?: number;
      rectangle?: boolean;
      /** Format: double */
      area?: number;
      centroid?: components["schemas"]["Point"];
      interiorPoint?: components["schemas"]["Point"];
      boundary?: components["schemas"]["Geometry"];
      /** Format: int32 */
      boundaryDimension?: number;
      envelopeInternal?: components["schemas"]["Envelope"];
    };
    GeometryFactory: {
      precisionModel?: components["schemas"]["PrecisionModel"];
      coordinateSequenceFactory?: components["schemas"]["CoordinateSequenceFactory"];
      /** Format: int32 */
      srid?: number;
    };
    /** @description Spesifikk metadata for en Grunnlinje. Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Diagram/Index/EAID_EEECEE48_B3FA_4807_AAE4_B30B63BC28E1 */
    GrunnlinjeMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      maritimeGrenser?: components["schemas"]["MaritimeGrenserMetadata"];
      kommunenummer?: components["schemas"]["Kommunenummer"];
    } & {
      common: unknown;
      commonGrense: unknown;
      maritimeGrenser: unknown;
    };
    /** @description Unik identifikasjon av et objekt */
    Identifikasjon: {
      /** @description Lokal id som identifiserer geometrien. Dette er en globalt unik id. */
      lokalid: string;
      /** @description Navnerom som unikt identifiserer datakilden til objektet, starter med to bokstavs kode jfr ISO 3166. */
      navnerom: string;
      /** @description Identifikasjon av en spesiell versjon av et geografisk objekt (instans), maksimum lengde på 25 karakterer. */
      versjonid?: string;
    };
    /** @description Representasjon av et kommunenummer */
    Kommunenummer: {
      /** @description Unik UUID for kommunenummeret */
      id: string;
      /**
       * Format: int32
       * @description Det faktiske kommunenummeret
       */
      kodeverdi?: number;
    };
    /** @description Egenskaper som beskriver konteksten som grensen sees i. */
    KontekstEgenskaper: {
      /** @description Id til objekt som det vises til i kontekst */
      id?: string;
      /**
       * @description Hvilken kontekst geometrien skal sees i
       * @enum {string}
       */
      type?: "FYLKE" | "KOMMUNE" | "NASJON";
      /** @description Angir om grensen skal leses med klokken for å danne flate. */
      retningMedKlokken: boolean;
      /**
       * Format: int32
       * @description Angir rekkefølgen på gitt grenselinje i flatedanningen.
       */
      rekkefoelge: number;
      /**
       * Format: int32
       * @description Angir hvilken flate for enheten grensen er en del av.
       */
      flateIndeks: number;
      /**
       * Format: int32
       * @description Angir om grensen er en del av et hull, og i så fall index på gitt hull.
       */
      hullIndeks?: number;
    };
    /** @description Metadata-egenskaper for maritim grense. */
    MaritimeGrenserMetadata: {
      /** @description Organisasjon som er ansvarlig for opprettholdelse av grensa. */
      ansvarligeMyndigheter: components["schemas"]["TekstHolder"][];
      /** @description Navn på område som loven gjelder for, eller område som grensa er beregnet fra. */
      gjelderOmraade?: string;
      /**
       * Format: date
       * @description Tidspunktet for når koordinatene er transformert fra originalt koordinatsystem.
       */
      transformasjonsdato?: string;
      /** @description Begrep knyttet til yttergrensa for virkeområdet, som oftest angitt i lov eller forskrift. */
      virkeomraadenavn?: string;
      /** @description Angivelse av hvilke land grensa er knyttet til Merknad: Alfanumerisk kode (ISO 3166-1 alpha-2) for land som definert i ISO 3166. */
      land: components["schemas"]["TekstHolder"][];
    };
    /** @description Diverse metadata-felter fra sosi-modellen. */
    Metadata: {
      discriminator: string;
    };
    /** @description Representasjon av en nasjon */
    NasjonResponse: {
      /** @description ID-en til nasjonen */
      id: string;
      /** @description Liste over navn til nasjonen */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalID til nasjonen */
      lokalid: string;
      /** @description Navnerommet til nasjonen */
      navnerom: string;
      features: components["schemas"]["FeatureCollection"];
    };
    Point: {
      envelope?: components["schemas"]["Geometry"];
      factory?: components["schemas"]["GeometryFactory"];
      userData?: { [key: string]: unknown };
      coordinates?: components["schemas"]["Coordinate"][];
      empty?: boolean;
      /** Format: int32 */
      dimension?: number;
      /** Format: double */
      x?: number;
      /** Format: double */
      y?: number;
      simple?: boolean;
      geometryType?: string;
      coordinate?: components["schemas"]["Coordinate"];
      /** Format: int32 */
      numPoints?: number;
      coordinateSequence?: components["schemas"]["CoordinateSequence"];
      boundary?: components["schemas"]["Geometry"];
      /** Format: int32 */
      boundaryDimension?: number;
      /** Format: double */
      length?: number;
      valid?: boolean;
      /** Format: int32 */
      srid?: number;
      /** Format: int32 */
      numGeometries?: number;
      precisionModel?: components["schemas"]["PrecisionModel"];
      rectangle?: boolean;
      /** Format: double */
      area?: number;
      centroid?: components["schemas"]["Point"];
      interiorPoint?: components["schemas"]["Point"];
      envelopeInternal?: components["schemas"]["Envelope"];
    };
    /** @description Beskrivelse av kvaliteten på stedfestingen */
    Posisjonskvalitet: {
      /** @description Metode for måling i grunnriss (x,y), og høyde (z) når metoden er den samme som ved måling i grunnriss. */
      maalemetode: string;
      /**
       * Format: int32
       * @description Punktstandardavviket i grunnriss for punkter samt tverravvik for linjer. Merknad: Oppgitt i cm.
       */
      noeyaktighet?: number;
    };
    PrecisionModel: {
      /** Format: double */
      scale?: number;
      type?: components["schemas"]["Type"];
      floating?: boolean;
      /** Format: int32 */
      maximumSignificantDigits?: number;
      /** Format: double */
      offsetX?: number;
      /** Format: double */
      offsetY?: number;
    };
    /** @description Spesifikk metadata for en riksgrense. Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Objekttype/Index/EAID_5C4B9E4D_05D7_4b2e_B467_9FCA428994F9 */
    RiksgrenseMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      /** @description Opplysning om at grense følger naturlige skillelinjer i terrenget. */
      foelgerTerrengdetalj?: string;
      /** @description Angivelse om stedfestingen (koordinatene) er kontrollert og funnet i orden (verifisert). */
      stedfestingVerifisert?: boolean;
      /** @description Organisasjon(er) som er ansvarlig for opprettholdelse av grensa. */
      ansvarligeMyndigheter?: components["schemas"]["TekstHolder"][];
      /**
       * Format: double
       * @description Bredde av området på begge sider av riksgrensen som er ryddet for vegetasjon høyere enn 0,5 m.
       */
      grensegateBredde?: number;
    } & {
      ansvarligeMyndigheter: unknown;
      common: unknown;
      commonGrense: unknown;
    };
    /** @description Angivelse av hvilke land grensa er knyttet til Merknad: Alfanumerisk kode (ISO 3166-1 alpha-2) for land som definert i ISO 3166. */
    TekstHolder: {
      /** @description ID for elementet. */
      id?: string;
      /** @description Tekstfelt. */
      beskrivelse: string;
    };
    /** @description Spesifikk metadata for en territorialgrense. Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Diagram/Index/EAID_EEECEE48_B3FA_4807_AAE4_B30B63BC28E1 */
    TerritorialgrenseMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      maritimeGrenser?: components["schemas"]["MaritimeGrenserMetadata"];
      /**
       * Format: date
       * @description Tidspunktet for når koordinatene er utregnet.
       */
      beregningsdato?: string;
    } & {
      common: unknown;
      commonGrense: unknown;
      maritimeGrenser: unknown;
    };
    Type: { [key: string]: unknown };
    /** @description Representasjon av en kommune */
    KommuneRequest: {
      /** @description Navnene til kommunen */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalId for angitt kommune */
      lokalid: string;
      /** @description Navnerommet for kommunen */
      navnerom?: string;
      /** @description UUID til kommunenummeret */
      kommunenummerId: string;
      /** @description Angir om kommunen er et samisk forvaltningsområde */
      samiskforvaltningsomraade: boolean;
    };
    KommuneResponse: {
      /** @description ID-en til kommunen */
      id: string;
      /** @description Liste over navn til kommunen */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalIDen til kommunen */
      lokalid: string;
      /** @description Navnerommet til kommunen */
      navnerom: string;
      kommunenummer: components["schemas"]["Kommunenummer"];
      /** @description Angir om kommunen er et samisk forvaltningsområde eller ikke */
      samiskforvaltningsomraade: boolean;
      /**
       * Format: date-time
       * @description Angir når denne kommunen ble sist oppdatert
       */
      oppdateringsdato: string;
      features: components["schemas"]["FeatureCollection"];
    };
    FylkeRequest: {
      /** @description Navnene til fylket */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalId for angitt fylke */
      lokalid: string;
      /** @description Navnerommet for fylket */
      navnerom: string;
      /** @description UUID til fylkesnummeret */
      fylkesnummerId: string;
      /** @description Angir om fylket er et samisk forvaltningsområde */
      samiskforvaltningsomraade: boolean;
    };
    /** @description Representasjon av et fylke */
    FylkeResponse: {
      /** @description ID-en til fylket */
      id: string;
      /** @description Liste over navn til fylket */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalIDen til fylket */
      lokalid: string;
      /** @description Navnerommet til fylket */
      navnerom: string;
      fylkesnummer: components["schemas"]["Fylkesnummer"];
      /** @description Angir om fylket er et samisk forvaltningsområde eller ikke */
      samiskforvaltningsomraade: boolean;
      /**
       * Format: date-time
       * @description Angir når dette fylket ble sist oppdatert
       */
      oppdateringsdato: string;
      features: components["schemas"]["FeatureCollection"];
    };
    /** @description Representasjon av et fylkesnummer */
    Fylkesnummer: {
      /** @description Unik UUID for fylkesnummeret */
      id: string;
      /**
       * Format: int32
       * @description Det faktiske fylkesnummeret
       */
      kodeverdi: number;
    };
    /** @description En referanse til en nasjon */
    NasjonRef: {
      /** @description ID-en til nasjonen */
      id: string;
      /** @description Liste over navn til nasjonen */
      navn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description URL til full representasjon av nasjonen */
      href: string;
    };
    /** @description En referanse til en historisk versjon av en administrativ enhet */
    HistorikkRef: {
      /**
       * Format: int32
       * @description IDen til den historiske revisjonen
       */
      revisionId: number;
      /**
       * Format: date-time
       * @description Når revisjonen ble opprettet
       */
      revisionDate: string;
      /**
       * @description Angir status for hva som medførte en ny revisjon
       * @enum {string}
       */
      historikkStatus: "NY" | "ENDRET" | "SLETTET";
      /** @description Referanse til hvor den historiske revisjonen kan finnes */
      href: string;
    };
    /** @description En referanse til en kommune */
    KommuneRef: {
      /** @description ID-en til kommunen */
      id: string;
      /** @description Liste over navn til kommunen */
      navn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description URL til full representasjon av kommunen */
      href: string;
    };
    /** @description Inneholder kodelisteinnslaget fra Geonorge. */
    GeonorgeKodelisteItem: {
      /** @description Id er en URL til kodelisteinnslaget hos Geonorge. */
      id: string;
      /** @description Kompakt tekst for framvisning. */
      label: string;
      /** @description Angir språket, no for norsk. */
      lang: string;
      /** @description Unik id. */
      uuid: string;
      /** @description Beskriver om kodelisteinnslaget er gyldig. */
      status: string;
      /** @description Beskrivelse av innslaget. */
      description: string;
      /** @description Numerisk kode. */
      codevalue: string;
    };
    KodelisteItem: {
      /**
       * @description Angir typen av eksternt forvaltet kodeliste.
       * @enum {string}
       */
      type: "KOMMUNENUMMER" | "FYLKESNUMMER" | "MAALEMETODE_KODE";
      item: components["schemas"]["GeonorgeKodelisteItem"];
    };
    /** @description En referanse til et fylke */
    FylkeRef: {
      /** @description ID-en til fylket */
      id: string;
      /** @description Liste over navn til fylket */
      navn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description URL til full representasjon av fylket */
      href: string;
    };
  };
}

export interface operations {
  /** Henter nasjon med gitt id */
  hentEn: {
    parameters: {
      path: {
        /** ID-en til nasjonen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["NasjonRef"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["NasjonResponse"];
        };
      };
    };
  };
  oppdaterNasjon: {
    parameters: {
      path: {
        /** ID til nasjonen man vil oppdatere */
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["NasjonResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NasjonRequest"];
      };
    };
  };
  /** Henter kommune med gitt id */
  hentEn_1: {
    parameters: {
      path: {
        /** ID-en til kommunen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["KommuneResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["KommuneResponse"];
        };
      };
    };
  };
  /** Oppdaterer angitt kommune. Returnerer den oppdaterte kommunen */
  oppdaterKommune: {
    parameters: {
      path: {
        /** ID til kommunen man vil oppdatere */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["KommuneResponse"];
        };
      };
      /** Bad request. Check the request body and path */
      400: {
        content: {
          "application/json": components["schemas"]["KommuneResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KommuneRequest"];
      };
    };
  };
  /** Henter fylke med gitt id */
  hentEn_2: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FylkeRef"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FylkeResponse"];
        };
      };
    };
  };
  oppdaterFylke: {
    parameters: {
      path: {
        /** ID til fylket man vil oppdatere */
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["FylkeResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FylkeRequest"];
      };
    };
  };
  /** Invaliderer kodeliste-cache slik at kodelister refreshes. */
  invalidateKodelisteCache: {
    responses: {
      /** Successful operation */
      200: unknown;
    };
  };
  importer: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": string;
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: binary */
          file: string;
        };
      };
    };
  };
  lagreGrenser: {
    responses: {
      /** Successful operation */
      200: unknown;
      /** Bad request */
      400: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeatureCollection"];
      };
    };
  };
  /** Henter alle nasjoner i nasjonal inndelingsbase. */
  hentAlle: {
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["NasjonRef"][];
        };
      };
    };
  };
  /** Henter historikken til en nasjon med gitt id */
  hentHistorikkForEn: {
    parameters: {
      path: {
        /** ID-en til nasjonen man vil hente historikk for */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["HistorikkRef"][];
        };
      };
    };
  };
  /** Henter en gitt revisjon av en historisk nasjon */
  hentHistorikkRevisjon: {
    parameters: {
      path: {
        /** Id til nasjonen man vil hente */
        id: string;
        /** Id til revisjonen man vil hente */
        revision: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["NasjonResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["NasjonResponse"];
        };
      };
    };
  };
  /** Henter grensene til en nasjon med gitt id */
  hentGrenser: {
    parameters: {
      path: {
        /** ID-en til nasjonen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  /** Henter alle kommuner i nasjonal inndelingsbase. */
  hentAlle_1: {
    parameters: {
      query: {
        /** Valgfri id til et fylke for å filtrere kommuner innenfor et fylke */
        fylkeid?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["KommuneRef"][];
        };
      };
    };
  };
  /** Henter historikken til en kommune med gitt id */
  hentHistorikkForEn_1: {
    parameters: {
      path: {
        /** ID-en til kommunen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["HistorikkRef"][];
        };
      };
    };
  };
  /** Henter en gitt revisjon av en historisk kommune */
  hentHistorikkRevisjon_1: {
    parameters: {
      path: {
        /** ID-en til kommunen man vil hente */
        id: string;
        /** RevisjonsId til revisjonen man vil hente */
        revision: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["KommuneResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["KommuneResponse"];
        };
      };
    };
  };
  /** Henter grensene til en kommune med gitt id */
  hentGrenser_1: {
    parameters: {
      path: {
        /** ID-en til kommunen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  fetchMaalemetodeKoder: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["KodelisteItem"][];
        };
      };
    };
  };
  fetchKommunenumre: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["KodelisteItem"][];
        };
      };
    };
  };
  fetchFylkesnumre: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["KodelisteItem"][];
        };
      };
    };
  };
  /** Henter territorialgrense med gitt id */
  hentTerritorialsgrense: {
    parameters: {
      path: {
        /** ID-en til territorialgrensen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Feature"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["Feature"];
        };
      };
    };
  };
  /** Henter historikk for territorialgrense med gitt id */
  hentTerritorialgrenseHistorikk: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["HistorikkRef"][];
        };
      };
    };
  };
  /** Henter gitt revisjon for gitt territorialgrense */
  hentTerritorialgrenseRevisjon: {
    parameters: {
      path: {
        /** ID til territorialgrensen man vil hente */
        id: string;
        /** ID til revisjonen man vil hente */
        revision: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Feature"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["Feature"];
        };
      };
    };
  };
  /** Henter riksgrense med gitt id */
  hentRiksgrense: {
    parameters: {
      path: {
        /** ID-en til riksgrensen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Feature"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["Feature"];
        };
      };
    };
  };
  /** Henter historikk for riksgrense med gitt id */
  hentRiksgrenseHistorikk: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["HistorikkRef"][];
        };
      };
    };
  };
  /** Henter gitt revisjon for gitt riksgrense */
  hentRiksgrenseRevisjon: {
    parameters: {
      path: {
        /** ID til riksgrense man vil hente */
        id: string;
        /** ID til revisjonen man vil hente */
        revision: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Feature"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["Feature"];
        };
      };
    };
  };
  /** Henter kommunegrense med gitt id */
  hentKommunegrense: {
    parameters: {
      path: {
        /** ID-en til kommunegrensen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Feature"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["Feature"];
        };
      };
    };
  };
  /** Henter historikk for kommunegrense med gitt id */
  hentKommunegrenseHistorikk: {
    parameters: {
      path: {
        /** ID-en til kommunen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["HistorikkRef"][];
        };
      };
    };
  };
  /** Henter gitt revisjon for gitt kommunegrense */
  hentKommunegrenseRevisjon: {
    parameters: {
      path: {
        /** ID til kommunegrensen man vil hente */
        id: string;
        /** ID til revisjonen man vil hente */
        revision: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Feature"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["Feature"];
        };
      };
    };
  };
  /** Henter fylkesgrense med gitt id */
  hentFylkesgrense: {
    parameters: {
      path: {
        /** ID-en til fylkesgrensen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Feature"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["Feature"];
        };
      };
    };
  };
  /** Henter historikk for fylkesgrense med gitt id */
  hentFylkesgrenseHistorikk: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["HistorikkRef"][];
        };
      };
    };
  };
  /** Henter gitt revisjon for gitt fylkesgrense */
  hentFylkesgrenseRevisjon: {
    parameters: {
      path: {
        /** ID til fylkesgrensen man vil hente */
        id: string;
        /** ID til revisjonen man vil hente */
        revision: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Feature"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["Feature"];
        };
      };
    };
  };
  /** Henter avtalt avgrensningslinje med gitt id */
  hentAvtaltavgrensningslinje: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Feature"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["Feature"];
        };
      };
    };
  };
  /** Henter historikk for avtalt avgrensningslinje med gitt id */
  hentAvtaltavgrensningslinjeHistorikk: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["HistorikkRef"][];
        };
      };
    };
  };
  /** Henter gitt revisjon for gitt avtalt avgrensningslinje */
  hentAvtaltavgrensningslinjeRevisjon: {
    parameters: {
      path: {
        /** ID til avtaltavgrensningslinje man vil hente */
        id: string;
        /** ID til revisjonen man vil hente */
        revision: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Feature"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["Feature"];
        };
      };
    };
  };
  /** Henter alle fylker i nasjonal inndelingsbase. */
  hentAlle_2: {
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FylkeRef"][];
        };
      };
    };
  };
  /** Henter historikken til et fylke med gitt id */
  hentHistorikkForEn_2: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente historikk for */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["HistorikkRef"][];
        };
      };
    };
  };
  /** Henter en gitt revisjon av et historisk fylke */
  hentHistorikkRevisjon_2: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
        /** RevisjonsId til revisjonen man vil hente */
        revision: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FylkeResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FylkeResponse"];
        };
      };
    };
  };
  /** Henter grensene til et fylke med gitt id */
  hentGrenser_2: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
}

export interface external {}
