/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/utkast/{id}": {
    /** Henter utkast med gitt id */
    get: operations["hentUtkast"];
    /** Oppdaterer angitt utkast. Returnerer oppdatert utkast. */
    put: operations["oppdaterUtkast"];
    /** Forkast angitt utkast. */
    delete: operations["forkastUtkast"];
  };
  "/v1/utkast": {
    /** Henter alle utkast i status Opprettet sortert på navn. */
    get: operations["hentUtkastIStatusOpprettet"];
    /** Oppretter et utkast og returnerer id. */
    post: operations["opprettUtkast"];
  };
  "/v1/utkast/{id}/publiser": {
    /** Publiserer utkastet med gitt id. */
    post: operations["publiserUtkast"];
  };
  "/v1/frontendlogger": {
    post: operations["logMelding"];
  };
  "/v1/stemmekretser/{lokalid}/framtidigeversjoner": {
    /** Returnerer en liste av nåværende Stemmekrets og eventuelt publiserte framtidige versjoner som matcher lokalid. */
    get: operations["hentFramtidigeVersjonerForStemmekrets"];
  };
  "/v1/stemmekretser/{id}": {
    /** Henter stemmekrets med gitt id */
    get: operations["hentStemmekrets"];
  };
  "/v1/stemmekretser/{id}/grenser": {
    /** Henter grensene til en stemmekrets med gitt id */
    get: operations["hentGrenserForStemmekrets"];
  };
  "/v1/nasjon/": {
    /** Henter nasjon på en gitt dato */
    get: operations["hentNasjon"];
  };
  "/v1/kommuner": {
    /** Henter alle kommuner i Nasjonal inndelingsbase. */
    get: operations["hentKommuner"];
  };
  "/v1/kommuner/{id}": {
    /** Henter kommune med gitt id */
    get: operations["hentKommune"];
  };
  "/v1/kommuner/{id}/stemmekretsgrenser": {
    get: operations["hentKommunesStemmekretsgrenser"];
  };
  "/v1/kommuner/{id}/stemmekretser": {
    /** Henter alle stemmekretser som tilhører en kommune. */
    get: operations["hentKommunesStemmekretser"];
  };
  "/v1/kommuner/{id}/inndelingerdeltgeometrigrenser": {
    get: operations["hentKommunesInndelingerMedDeltGeometriGrenser"];
  };
  "/v1/kommuner/{id}/inndelingerdeltgeometri": {
    get: operations["hentKommunesInndelingerMedDeltGeometri"];
  };
  "/v1/kommuner/{id}/grunnkretsgrenser": {
    get: operations["hentKommunesGrunnkretsgrenser"];
  };
  "/v1/kommuner/{id}/grunnkretser": {
    /** Henter alle grunnkretser som tilhører en kommune. */
    get: operations["hentKommunesGrunnkretser"];
  };
  "/v1/kommuner/{id}/grenser": {
    /** Henter grensene til en kommune med gitt id */
    get: operations["hentGrenserForKommune"];
  };
  "/v1/kodeliste/maalemetode-koder": {
    get: operations["fetchMaalemetodeKoder"];
  };
  "/v1/inndelinger/": {
    /** Søk etter inndelinger ved å bruke en søkestring */
    get: operations["finnInndelinger"];
  };
  "/v1/grunnkretser/{lokalid}/framtidigeversjoner": {
    /** Returnerer en liste av nåværende Grunnkrets og eventuelt publiserte framtidige versjoner som matcher lokalid. */
    get: operations["hentFramtidigeVersjonerForGrunnkrets"];
  };
  "/v1/grunnkretser/{id}": {
    /** Henter grunnkrets med gitt id */
    get: operations["hentGrunnkrets"];
  };
  "/v1/grunnkretser/{id}/grenser": {
    /** Henter grensene til en grunnkrets med gitt id */
    get: operations["hentGrenserForGrunnkrets"];
  };
  "/v1/fylker": {
    /** Henter alle fylker i Nasjonal inndelingsbase. */
    get: operations["hentFylker"];
  };
  "/v1/fylker/{id}": {
    /** Henter fylke med gitt id */
    get: operations["hentFylke"];
  };
  "/v1/fylker/{id}/stemmekretser": {
    get: operations["hentFylkesStemmekretser"];
  };
  "/v1/fylker/{id}/grunnkretser": {
    get: operations["hentFylkesGrunnkretser"];
  };
  "/v1/fylker/{id}/grenser": {
    /** Henter grensene til et fylke med gitt id */
    get: operations["hentGrenserForFylke"];
  };
  "/v1/ekstern/stemmekretser": {
    /** Henter stemmekretser med gitte id-er */
    get: operations["hentStemmekretserForIds"];
  };
  "/v1/ekstern/stemmekretser/{id}": {
    /** Henter stemmekrets med gitt id */
    get: operations["hentStemmekrets_1"];
  };
  "/v1/ekstern/stemmekretser/{id}/grenser": {
    /** Henter grensene til en stemmekrets med gitt id */
    get: operations["hentGrenserForStemmekrets_1"];
  };
  "/v1/ekstern/kommuner": {
    /** Henter alle kommuner i Nasjonal inndelingsbase. */
    get: operations["hentKommuner_1"];
  };
  "/v1/ekstern/kommuner/{kommunenummer}/stemmekretsermeddetaljer": {
    /** Henter alle stemmekretser med detaljer for gitt kommunenummer. Denne brukes for uthenting av data til dataplattform. */
    get: operations["hentAlleStemmekretserMedDetaljerForKommune"];
  };
  "/v1/ekstern/kommuner/{kommunenummer}/stemmekretser": {
    /** Henter alle stemmekretser for gitt kommunenummer */
    get: operations["hentAlleStemmekretserForKommune"];
  };
  "/v1/ekstern/kommuner/{kommunenummer}/grunnkretsermeddetaljer": {
    /** Henter alle grunnkretser med detaljer for gitt kommunenummer. Denne brukes for uthenting av data til dataplattform. */
    get: operations["hentAlleGrunnkretserMedDetaljerForKommune"];
  };
  "/v1/ekstern/kommuner/{kommunenummer}/grunnkretser": {
    /** Henter alle grunnkretser for gitt kommunenummer */
    get: operations["hentAlleGrunnkretserForKommune"];
  };
  "/v1/ekstern/kommuner/{id}": {
    /** Henter kommune med gitt id */
    get: operations["hentKommune_1"];
  };
  "/v1/ekstern/grunnkretser": {
    /** Henter grunnkretser med gitte id-er */
    get: operations["hentGrunnkretserForIds"];
  };
  "/v1/ekstern/grunnkretser/{id}/grenser": {
    /** Henter grensene til en grunnkrets med gitt id */
    get: operations["hentGrenserForGrunnkrets_1"];
  };
  "/v1/ekstern/fylker": {
    /** Henter alle fylker i Nasjonal inndelingsbase. */
    get: operations["hentFylker_1"];
  };
  "/v1/ekstern/fylker/{id}": {
    /** Henter fylke med gitt id */
    get: operations["hentFylke_1"];
  };
  "/v1/authz/status": {
    /** Henter status for autorisering */
    get: operations["getStatus"];
  };
}

export interface components {
  schemas: {
    /** @description Representasjon av et navn */
    AdministrativEnhetNavn: {
      /** @description Navnet på en administrativ enhet */
      navn: string;
      /** @description Språkkoden til det administrative navnet */
      spraak: string;
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
      /**
       * Format: int32
       * @description Rekkefølge på navn
       */
      rekkefoelge?: number;
    };
    /** @description Spesfikk metadata for en administrativ grense (fylkes/kommunegrense). Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Objekttype/Index/EAID_5142EDBA_4226_4ca3_924D_EECEFD216D1A */
    AdministrativGrenseMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      /** @description Henviser til fastsettings- eller lovinformasjon. */
      dokumentasjonsreferanser?: components["schemas"]["DokumentasjonsreferanseDTO"][];
    } & {
      common: unknown;
      commonGrense: unknown;
      dokumentasjonsreferanser: unknown;
    };
    /** @description Spesifikk metadata for en AvtaltAvgrensningslinje. Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Diagram/Index/EAID_EEECEE48_B3FA_4807_AAE4_B30B63BC28E1 */
    AvtaltAvgrensningslinjeMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      /** @description Henviser til fastsettings- eller lovinformasjon. */
      dokumentasjonsreferanser?: components["schemas"]["DokumentasjonsreferanseDTO"][];
    } & {
      common: unknown;
      commonGrense: unknown;
      dokumentasjonsreferanser: unknown;
    };
    /** @description Felles metadata-egenskaper for grenser. */
    CommonGrenseMetadata: {
      posisjonskvalitet?: components["schemas"]["Posisjonskvalitet"];
    };
    /** @description Felles metadata-egenskaper. */
    CommonMetadata: {
      identifikasjon: components["schemas"]["Identifikasjon"];
      /**
       * Format: date-time
       * @description Dato når objektet siste gang ble registrert/observert/målt i terrenget
       */
      datafangstdato?: string;
      /**
       * Format: date
       * @description Tidspunktet når objektet oppstod i den virkelige verden
       */
      gyldigFra: string;
      /**
       * Format: date
       * @description Tidspunktet når objektet opphørte å eksistere i den virkelige verden
       */
      gyldigTil?: string;
      /** @description Generelle opplysninger/merknad */
      informasjon?: string;
      sporingsinformasjon: components["schemas"]["Sporingsinformasjon"];
      /** @description Referanse til opphavsmaterialet, kildematerialet, organisasjons/publiseringskilde. */
      opphav?: string;
    };
    /** @description Henviser til fastsettings- eller lovinformasjon. */
    DokumentasjonsreferanseDTO: {
      /** @description ID for dokumentasjonsreferansen. */
      id?: string;
      /** @description URL til saksdokument. */
      dokumentlenker: components["schemas"]["TekstHolder"][];
      /**
       * Format: date
       * @description Dato for når dokumentet ble skrevet, publisert eller revidert.
       */
      fastsettingsdato: string;
      /** @description Offentlig instans som har fastsatt en grense. */
      fastsettingsmyndighet?: string;
      /** @description Lov som rettskilden er begrunnet i. */
      hjemmel?: string;
      /** @description Henvisning til saksdokument i Kartverkets eget arkiv. */
      internReferanserKartverket: components["schemas"]["TekstHolder"][];
      /** @description Referanse til lov, forskrift, vedtak, dom eller traktat i form av kode som angir type dokument, dato og nummer For eksempel: LOV-2012-09-07-65. */
      rettskildeId?: string;
      /** @description Navn på lov, forskrift, vedtak, dom eller traktat. */
      rettskildeTittel: string;
      /**
       * Format: date
       * @description Tidspunktet når objektet oppstod i den virkelige verden (Vedtakets gyldighet). Påkrevd for alle nye dokumentasjonsreferanser.
       */
      vedtakGyldigFra?: string;
      /**
       * Format: date
       * @description Tidspunktet når objektet opphørte å eksistere i den virkelige verden (Vedtakets gyldighet)
       */
      vedtakGyldigTil?: string;
      /** @description Egenskap som sier om en dokumentasjonsreferanse skal arkiveres */
      shouldArchive: boolean;
    };
    /** @description Liste av features som holder på dataene */
    Feature: {
      /** @description En konstant, navn: type, verdi: Feature */
      type: string;
      /** @description Id til feature */
      id?: string;
      properties: components["schemas"]["FeatureProperties"];
      geometry: components["schemas"]["Geometry"];
    };
    /** @description Egenskaper som beskriver en gitt feature (properties-objektet i geojson-strukturen) */
    FeatureProperties: {
      /** @description Avhengig av hva slags feature man har kan dette være enten grensetype eller geometri-type (posisjon eller flate) */
      type: string;
      /**
       * Format: int32
       * @description Koordinatsystemet. Defaulter til 25833.
       */
      srid: number;
      metadata?: components["schemas"]["Metadata"];
      /** @description Egenskaper til konteksten til grensen. */
      kontekstEgenskaper: components["schemas"]["KontekstEgenskaper"][];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
      /** @description Egenskap som sier om en grense med en grenseendring er skal arkiveres */
      shouldArchive: boolean;
    };
    /** @description Metadata for en flate (felles for nasjon, fylke, kommune og grunnkrets) */
    FlateMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
    } & {
      common: unknown;
    };
    /** @description Endringer på fylke. */
    FylkeRequest: {
      /** @description Navnene til fylket */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalId for angitt fylke */
      lokalid: string;
      /** @description Angir om fylket er et samisk forvaltningsområde */
      samiskforvaltningsomraade: boolean;
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Geometry-typene vi støtter i NIBAS. */
    Geometry: {
      type: string;
    };
    /** @description Representasjon av endringer på grensegeometri. */
    Grenseendringer: {
      /** @description Endringer på features. */
      endredeFeatures: components["schemas"]["Feature"][];
    };
    /** @description Representasjon av en grunnkrets */
    GrunnkretsRequest: {
      /** @description Navnet på grunnkretsen */
      navn: string;
      /** @description Grunnkretsnummeret til grunnkretsen */
      nummer: string;
      identifikasjon: components["schemas"]["Identifikasjon"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Representasjon av sammenslåing av en grunnkrets med 1 eller flere andre grunnkretser i samme kommune */
    GrunnkretsSammenslaaingsendringRequest: {
      viderefoertGrunnkrets: components["schemas"]["IdentifikatorMedVersjon"];
      /** @description Liste av identifikatorer som skal bli del av den videreførte grunnkretsen */
      grunnkretserTilSammenslaaing: components["schemas"]["IdentifikatorMedVersjon"][];
      /** @description Navnet til den sammenslåtte grunnkretsen */
      navn: string;
      /** @description Grunnkretsnummeret til den sammenslåtte grunnkretsen */
      nummer: string;
    };
    /** @description Spesifikk metadata for en Grunnlinje. Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Diagram/Index/EAID_EEECEE48_B3FA_4807_AAE4_B30B63BC28E1 */
    GrunnlinjeMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      /** @description Henviser til fastsettings- eller lovinformasjon. */
      dokumentasjonsreferanser?: components["schemas"]["DokumentasjonsreferanseDTO"][];
    } & {
      common: unknown;
      commonGrense: unknown;
      dokumentasjonsreferanser: unknown;
    };
    /** @description Unik identifikasjon av et objekt */
    Identifikasjon: {
      /** @description Lokal id som identifiserer geometrien. Dette er en globalt unik id. */
      lokalid: string;
    };
    /** @description Identifikator av en stemmekrets eller grunnkrets */
    IdentifikatorMedVersjon: {
      /** @description LokalId for stemmekrets/grunnkretsen */
      lokalId: string;
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Metode for måling i grunnriss (x,y), og høyde (z) når metoden er den samme som ved måling i grunnriss. */
    KodelisteEntry: {
      /** @description Id for kodeliste-innslaget. */
      id?: string;
      /** @description Lenke til kodelista. */
      href: string;
    };
    /** @description Representasjon av en kommune */
    KommuneRequest: {
      /** @description Navnene til kommunen */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalId for angitt kommune */
      lokalid: string;
      /** @description Angir om kommunen er et samisk forvaltningsområde */
      samiskforvaltningsomraade: boolean;
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Egenskaper som beskriver konteksten som grensen sees i. */
    KontekstEgenskaper: {
      id?: components["schemas"]["ObjektIdentifikator"];
      kommuneId?: components["schemas"]["ObjektIdentifikator"];
      /** @description kretsnummeret til konteksten */
      kretsNummer?: string;
      /**
       * @description Hvilken kontekst geometrien skal sees i
       * @enum {string}
       */
      type: "GRUNNKRETS" | "STEMMEKRETS";
      /**
       * Format: int32
       * @description Teknisk versjon til referert objekt for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Representasjon av deling av en krets som ender i to kretser der én er videreført og én er ny */
    KretsDelingEndringRequest: {
      opprinneligKrets: components["schemas"]["IdentifikatorMedVersjon"];
      kommuneId: components["schemas"]["ObjektIdentifikator"];
      /**
       * @description Flatetypen som skal deles
       * @enum {string}
       */
      flatetype: "FYLKE" | "KOMMUNE" | "NASJON" | "GRUNNKRETS" | "STEMMEKRETS" | "SKOLEKRETS";
      /** @description Navn og nummer for de nye kretsene som skal utledes fra opprinnelig krets */
      nyeKretser: components["schemas"]["KretsNavnOgNummer"][];
    };
    /** @description Representasjon av navn og nummer for en ny krets */
    KretsNavnOgNummer: {
      /** @description Navne til den nye kretsen som skal dannes fra opprinneligKrets */
      kretsNavn: string;
      /** @description Grunnkrets/stemmekrets-nummmer til den nye kretsen */
      kretsNummer: string;
    };
    /** @description Wrapper-objekt rundt en JTS LineString. */
    LineString: components["schemas"]["Geometry"] & {
      /** @description Geometriens type. Diskriminator. */
      type?: string;
      /** @description Liste av (x og y som liste). */
      coordinates?: number[][];
    } & {
      coordinates: unknown;
      type: unknown;
    };
    Lokalid: {
      value: string;
    };
    /** @description Diverse metadata-felter fra sosi-modellen. */
    Metadata: {
      discriminator: string;
    };
    /** @description Representasjon av endringer på metadata. */
    Metadataendringer: {
      /** @description Endringer på nasjon. */
      nasjonsendringer: {
        [key: string]: components["schemas"]["NasjonRequest"];
      };
      /** @description Endringer på fylke. */
      fylkesendringer: { [key: string]: components["schemas"]["FylkeRequest"] };
      /** @description Endringer på kommune. */
      kommuneendringer: {
        [key: string]: components["schemas"]["KommuneRequest"];
      };
      /** @description Endringer på grunnkrets. */
      grunnkretsendringer: {
        [key: string]: components["schemas"]["GrunnkretsRequest"];
      };
      /** @description Endringer på stemmekrets. */
      stemmekretsendringer: {
        [key: string]: components["schemas"]["StemmekretsRequest"];
      };
    };
    /** @description Wrapper-objekt rundt et JTS MultiPolygon. */
    MultiPolygon: components["schemas"]["Geometry"] & {
      /** @description Geometriens type. Diskriminator. */
      type?: string;
      /** @description Liste av polygonenes liste av LinearRings som igjen har liste av koordinater som er liste av x og y. */
      coordinates?: number[][][][];
    } & {
      coordinates: unknown;
      type: unknown;
    };
    /** @description Endringer på nasjon. */
    NasjonRequest: {
      /** @description Navnene til nasjonen */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalId for angitt nasjon */
      lokalid: string;
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Id til kommunen som konteksten ligger i */
    ObjektIdentifikator: {
      lokalid: components["schemas"]["Lokalid"];
      /** Format: date */
      gyldighetsdato: string;
    };
    /** @description Representasjon av operasjoner/handlinger som er utført i klienten. */
    Operasjoner: {
      metadataendringer: components["schemas"]["Metadataendringer"];
      grenseendringer: components["schemas"]["Grenseendringer"];
      stemmekretsSammenslaaingsendring?: components["schemas"]["StemmekretsSammenslaaingsendringRequest"];
      grunnkretsSammenslaaingsendring?: components["schemas"]["GrunnkretsSammenslaaingsendringRequest"];
      /** @description Deling av en stemmekrets eller grunnkrets */
      kretsDelingEndringer: components["schemas"]["KretsDelingEndringRequest"][];
    };
    /** @description Representasjon for oppdatering av utkast */
    OppdaterUtkastRequest: {
      /** @description Arbeidsnavnet til utkastet. */
      navn: string;
      /** @description Typen endring utkastet representerer. */
      endringstype: string;
      operasjoner: components["schemas"]["Operasjoner"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Wrapper-objekt rundt en JTS Point. */
    Point: components["schemas"]["Geometry"] & {
      /** @description Geometriens type. Diskriminator. */
      type?: string;
      /** @description X og y som liste. */
      coordinates?: number[];
    } & {
      coordinates: unknown;
      type: unknown;
    };
    /** @description Beskrivelse av kvaliteten på stedfestingen */
    Posisjonskvalitet: {
      maalemetode: components["schemas"]["KodelisteEntry"];
      /**
       * Format: int32
       * @description Punktstandardavviket i grunnriss for punkter samt tverravvik for linjer. Merknad: Oppgitt i cm.
       */
      noeyaktighet?: number;
    };
    /** @description Spesifikk metadata for en riksgrense. Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Objekttype/Index/EAID_5C4B9E4D_05D7_4b2e_B467_9FCA428994F9 */
    RiksgrenseMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      /** @description Henviser til fastsettings- eller lovinformasjon. */
      dokumentasjonsreferanser?: components["schemas"]["DokumentasjonsreferanseDTO"][];
    } & {
      common: unknown;
      commonGrense: unknown;
      dokumentasjonsreferanser: unknown;
    };
    /** @description Holder på informasjon om endring av objektet. */
    Sporingsinformasjon: {
      /**
       * Format: date-time
       * @description Dato for siste endring på objektdataene
       */
      oppdateringsdato: string;
    };
    /** @description Spesifikk metadata for en statistisk grense (grunnkrets/delområde). Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Objekttype/Index/EAID_374BE5B3_5F8B_498a_8F53_9CCA72619C36 */
    StatistiskgrenseMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
    } & {
      common: unknown;
      commonGrense: unknown;
    };
    /** @description Representasjon av en stemmekrets */
    StemmekretsRequest: {
      /** @description Stemmekretsnavnet til stemmekretsen */
      navn?: string;
      /** @description Stemmekretsnummeret til stemmekretsen */
      nummer?: string;
      identifikasjon: components["schemas"]["Identifikasjon"];
      /** @description Tellekretsnummeret til stemmekretsen */
      tellekretsnummer?: string;
      /** @description Tellekretsnavnet til stemmekretsen */
      tellekretsnavn?: string;
      /** @description Valgdistriktsnummeret til stemmekretsen */
      valgdistriktsnummer?: string;
      /** @description Kommunenummeret stemmekretsen tilhører til */
      kommunenummer?: string;
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Representasjon av sammenslåing av en stemmekrets med 1 eller flere andre stemmekretser i samme kommune */
    StemmekretsSammenslaaingsendringRequest: {
      viderefoertStemmekrets: components["schemas"]["IdentifikatorMedVersjon"];
      /** @description Liste av identifikatorer som skal bli del av den videreførte stemmekretsen */
      stemmekretserTilSammenslaaing: components["schemas"]["IdentifikatorMedVersjon"][];
      /** @description Navnet til den sammenslåtte stemmekretsen */
      navn: string;
      /** @description Stemmekretsnummeret til den sammenslåtte stemmekretsen */
      nummer: string;
    };
    /** @description Henvisning til saksdokument i Kartverkets eget arkiv. */
    TekstHolder: {
      /** @description ID for elementet. */
      id?: string;
      /** @description Tekstfelt. */
      beskrivelse: string;
    };
    /** @description Spesifikk metadata for en territorialgrense. Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Diagram/Index/EAID_EEECEE48_B3FA_4807_AAE4_B30B63BC28E1 */
    TerritorialgrenseMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      /** @description Henviser til fastsettings- eller lovinformasjon. */
      dokumentasjonsreferanser?: components["schemas"]["DokumentasjonsreferanseDTO"][];
    } & {
      common: unknown;
      commonGrense: unknown;
      dokumentasjonsreferanser: unknown;
    };
    ApiErrorResponse: {
      /** @description En unik feilkode for denne feilen som kan vises til bruker. Denne feilkoden burde også være med i loggene så man finner igjen feilen som oppstod. */
      errorCode: string;
      errorDescription: components["schemas"]["ErrorDescription"];
    };
    /** @description En forklaring av feilen som oppstod. Denne er ment til å kunne vises direkte til brukeren. */
    ErrorDescription: {
      /** @description Tittelen på feilmeldingen som skal vises. */
      title: string;
      /** @description En beskrivende forklaring av feilen som oppstod. */
      description: string;
      /** @description Litt tilleggsinfo relatert til feilen om man vil gi noe mer forklaring av konteksten. Ikke obligatorisk. */
      additionalInfo?: string;
    };
    /** @description Feil som har oppstått pga optimistisk lås. */
    OptimistiskLaasResponse: {
      /** @description Identifikatoren til objektet som er utdatert. */
      id: string;
      /** @description Typen til objektet som er utdatert. */
      type: string;
      /**
       * Format: int32
       * @description Versjon som prøves å oppdateres.
       */
      versjon: number;
      /**
       * Format: int32
       * @description Versjon som er gjeldende for objektet nå.
       */
      gjeldendeVersjon: number;
      /** @description Beskrivelse av hva som har gått galt. */
      melding?: string;
    };
    OptimistiskLaasWrapper: {
      /**
       * @description HttpStatus for responsen.
       * @enum {string}
       */
      httpStatus:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      /** @description Feil som har oppstått pga optimistisk lås. */
      optimisticLockExceptions: components["schemas"]["OptimistiskLaasResponse"][];
    };
    /** @description Representasjon av audit info for et objekt. */
    AuditInfoResponse: {
      /**
       * Format: date-time
       * @description Da objektet sist ble oppdatert.
       */
      oppdateringsdato: string;
    };
    /** @description Representasjon av utkast */
    UtkastResponse: {
      /** @description Unik uuid for utkastet */
      id: string;
      /** @description Arbeidsnavnet til utkastet. */
      navn: string;
      /** @description Typen endring utkastet representerer. */
      endringstype: string;
      /** @description Status for utkastet. */
      status: string;
      /**
       * Format: date-time
       * @description Da utkastet ble opprettet.
       */
      opprettetDato: string;
      auditInfoResponse: components["schemas"]["AuditInfoResponse"];
      operasjoner: components["schemas"]["Operasjoner"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Utkastet som ønskes opprettet */
    OpprettUtkastRequest: {
      /** @description Arbeidsnavnet til utkastet. */
      navn: string;
      /** @description Typen endring utkastet representerer. */
      endringstype: string;
    };
    /** @description Requestbody for publisering av utkast. */
    PubliserUtkastRequest: {
      /**
       * Format: date
       * @description Datoen utkastet skal publiseres fra. Settes default til dagens dato om ikke satt.
       */
      publiseringsdato: string;
    };
    FrontendLogRequest: {
      /** @enum {string} */
      logLevel: "INFO" | "WARN" | "ERROR";
      message: string;
      stacktrace?: string;
    };
    /** @description En referanse til et utkast */
    UtkastRef: {
      /** @description ID-en til utkastet */
      id: string;
      /** @description Navnet på utkastet */
      navn: string;
      /** @description URL til full representasjon av utkastet. */
      href: string;
      /**
       * Format: date-time
       * @description Tidspunktet utkastet ble opprettet.
       */
      opprettetDato: string;
    };
    /** @description Gyldighetsintervall for objektet */
    GyldighetResponse: {
      /**
       * Format: date
       * @description Tidspunktet objektet er gyldig fra
       */
      gyldigFra: string;
      /**
       * Format: date
       * @description Tidspunktet objektet er gyldig til. Kan være tomt/løpende.
       */
      gyldigTil?: string | null;
    };
    /** @description Representasjon av et kommunenummer */
    Kommunenummer: {
      /** @description Unik UUID for kommunenummeret */
      id: string;
      /** @description Det faktiske kommunenummeret */
      kodeverdi: string;
    };
    /** @description Representasjon av en stemmekrets */
    StemmekretsResponse: {
      id: components["schemas"]["ObjektIdentifikator"];
      /** @description Navnet på stemmekretsen */
      navn: string;
      /** @description Stemmekretsnummeret til stemmekretsen */
      nummer: string;
      gyldighet: components["schemas"]["GyldighetResponse"];
      /** @description Typen endring som ble gjort på objektet */
      endringstype?: string;
      /**
       * Format: date-time
       * @description Siste oppdateringstidspunkt for objektet
       */
      oppdateringsdato: string;
      /**
       * Format: date-time
       * @description Datafangsdato for objektet
       */
      datafangstdato?: string;
      kommunenummer: components["schemas"]["Kommunenummer"];
      kommuneIdentifikator: components["schemas"]["ObjektIdentifikator"];
      /** @description Tellekretsnummer til stemmekretsen */
      tellekretsnummer?: string;
      /** @description Tellekretsnavn til stemmekretsen */
      tellekretsnavn?: string;
      /** @description Valgdistriktsnummer til stemmekretsen */
      valgdistriktsnummer?: string;
      representasjonspunkt: components["schemas"]["Feature"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Geometrien til fylket. Ikke grenser */
    FeatureCollection: {
      /** @description Toppnivå for geojson-strukturen, definert av en konstant med navn type og verdi FeatureCollection */
      type: string;
      /** @description Liste av features som holder på dataene */
      features: components["schemas"]["Feature"][];
    };
    /** @description Representasjon av nasjon */
    NasjonResponse: {
      id: components["schemas"]["ObjektIdentifikator"];
      /** @description Liste over navn til nasjon */
      navn: components["schemas"]["AdministrativEnhetNavn"][];
      gyldighet: components["schemas"]["GyldighetResponse"];
      omraade?: components["schemas"]["MultiPolygon"];
      representasjonspunkt: components["schemas"]["Feature"];
      /**
       * Format: date-time
       * @description Angir når denne nasjonen ble sist oppdatert
       */
      oppdateringsdato: string;
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Representasjon av en kommune */
    KommuneResponse: {
      id: components["schemas"]["ObjektIdentifikator"];
      /** @description Lokal-id til fylket denne kommunen er i */
      fylkeId: string;
      /** @description Liste over navn til kommunen */
      navn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description Kommunenummeret til kommunen */
      nummer: string;
      gyldighet: components["schemas"]["GyldighetResponse"];
      /** @description Angir om kommunen er et samisk forvaltningsområde eller ikke */
      samiskforvaltningsomraade: boolean;
      /**
       * Format: date-time
       * @description Angir når denne kommunen ble sist oppdatert
       */
      oppdateringsdato: string;
      representasjonspunkt: components["schemas"]["Feature"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    InndelingResponse: {
      id: components["schemas"]["ObjektIdentifikator"];
      /**
       * @description Flatetypen til inndelingen
       * @enum {string}
       */
      type: "FYLKE" | "KOMMUNE" | "NASJON" | "GRUNNKRETS" | "STEMMEKRETS" | "SKOLEKRETS";
      /** @description Navnet til inndelingen */
      navn: string;
      /** @description Nummeret til inndelingen */
      nummer: string;
      representasjonspunkt: components["schemas"]["Feature"];
      gyldighet: components["schemas"]["GyldighetResponse"];
    };
    /** @description Representasjon av en grunnkrets */
    GrunnkretsResponse: {
      id: components["schemas"]["ObjektIdentifikator"];
      /** @description Navnet på grunnkretsen */
      navn: string;
      /** @description Grunnkretsnummeret til grunnkretsen */
      nummer: string;
      gyldighet: components["schemas"]["GyldighetResponse"];
      /**
       * Format: date-time
       * @description Siste oppdateringstidspunkt for objektet
       */
      oppdateringsdato: string;
      /**
       * Format: date-time
       * @description Datafangsdato for objektet
       */
      datafangstdato?: string;
      kommunenummer: components["schemas"]["Kommunenummer"];
      kommuneIdentifikator: components["schemas"]["ObjektIdentifikator"];
      /** @description Typen endring som ble gjort på objektet */
      endringstype?: string;
      representasjonspunkt: components["schemas"]["Feature"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Liste av kodeliste-elementer. */
    KodelisteItem: {
      /** @description Id til kodeliste-innslaget. */
      id: string;
      /** @description kode til kodeliste-innslaget. */
      kode: string;
      /** @description Navnet til kodeliste-innslaget. */
      label: string;
    };
    KodelisteRespons: {
      /**
       * @description Angir typen av kodeliste.
       * @enum {string}
       */
      type: "KOMMUNENUMMER" | "FYLKESNUMMER" | "MAALEMETODE_KODE";
      /** @description Liste av kodeliste-elementer. */
      items: components["schemas"]["KodelisteItem"][];
    };
    /** @description Koordinatet til representasjonspunktet til inndelingen. */
    Coordinate: {
      /** Format: double */
      x?: number;
      /** Format: double */
      y?: number;
      /** Format: double */
      z?: number;
      valid?: boolean;
      /** Format: double */
      m?: number;
      coordinate?: components["schemas"]["Coordinate"];
    };
    InndelingSearchResponse: {
      /** @description Lokalid til inndelingen */
      id: string;
      /**
       * @description Flatetypen til inndelingen
       * @enum {string}
       */
      type: "FYLKE" | "KOMMUNE" | "NASJON" | "GRUNNKRETS" | "STEMMEKRETS" | "SKOLEKRETS";
      /** @description Navnet til inndelingen */
      navn: string;
      /** @description Nummeret til inndelingen */
      nummer: string;
      representasjonspunkt: components["schemas"]["Coordinate"];
    };
    /** @description Representasjon av et fylke */
    FylkeResponse: {
      id: components["schemas"]["ObjektIdentifikator"];
      /** @description Liste over navn til fylket */
      navn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description Fylkesnummeret til fylket */
      nummer: string;
      gyldighet: components["schemas"]["GyldighetResponse"];
      /** @description Angir om fylket er et samisk forvaltningsområde eller ikke */
      samiskforvaltningsomraade: boolean;
      /**
       * Format: date-time
       * @description Angir når dette fylket ble sist oppdatert
       */
      oppdateringsdato: string;
      representasjonspunkt: components["schemas"]["Feature"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Representasjon av en krets. Response-type kun for Matrikkelen. Kan være grunnkrets, stemmekrets etc. */
    EksternKretsResponse: {
      /** @description Lokalid-en til kretsen. */
      id: string;
      /** @description Navnet på kretsen. */
      navn: string;
      /** @description Nummeret til kretsen. */
      nummer: string;
      kommunenummer: components["schemas"]["Kommunenummer"];
      features: components["schemas"]["FeatureCollection"];
    };
    /** @description Representasjon av en stemmekrets */
    EksternStemmekretsResponse: {
      id: components["schemas"]["ObjektIdentifikator"];
      gyldighet: components["schemas"]["GyldighetResponse"];
      /** @description Typen endring som ble gjort på objektet */
      endringstype?: string;
      /**
       * Format: date-time
       * @description Siste oppdateringstidspunkt for objektet
       */
      oppdateringsdato: string;
      /**
       * Format: date-time
       * @description Datafangsdato for objektet
       */
      datafangstdato?: string;
      /** @description Navnet på stemmekretsen */
      stemmekretsnavn: string;
      /** @description Stemmekretsnummeret til stemmekretsen */
      stemmekretsnummer: string;
      kommunenummer: components["schemas"]["Kommunenummer"];
      /** @description Tellekretsnummer til stemmekretsen */
      tellekretsnummer?: string;
      /** @description Tellekretsnavn til stemmekretsen */
      tellekretsnavn?: string;
      /** @description Valgdistriktsnummer til stemmekretsen */
      valgdistriktsnummer?: string;
      features: components["schemas"]["FeatureCollection"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description En referanse til en kommune */
    EksternKommuneRef: {
      id: components["schemas"]["ObjektIdentifikator"];
      /** @description Liste over navn til kommunen */
      navn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description URL til full representasjon av kommunen */
      href: string;
      kommunenummer: components["schemas"]["Kommunenummer"];
      /**
       * Format: int32
       * @description Antall publiserte framtidige gyldige versjoner.
       */
      antallFramtidigeVersjoner: number;
    };
    /** @description Representasjon av en grunnkrets */
    EksternGrunnkretsResponse: {
      id: components["schemas"]["ObjektIdentifikator"];
      /** @description Navnet på grunnkretsen */
      navn: string;
      /** @description Grunnkretsnummeret til grunnkretsen */
      grunnkretsnummer: string;
      gyldighet: components["schemas"]["GyldighetResponse"];
      /**
       * Format: date-time
       * @description Siste oppdateringstidspunkt for objektet
       */
      oppdateringsdato: string;
      /**
       * Format: date-time
       * @description Datafangsdato for objektet
       */
      datafangstdato?: string;
      kommunenummer: components["schemas"]["Kommunenummer"];
      /** @description Typen endring som ble gjort på objektet */
      endringstype?: string;
      features: components["schemas"]["FeatureCollection"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Representasjon av en kommune */
    EksternKommuneResponse: {
      id: components["schemas"]["ObjektIdentifikator"];
      /** @description Liste over navn til kommunen */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      kommunenummer: components["schemas"]["Kommunenummer"];
      /** @description Angir om kommunen er et samisk forvaltningsområde eller ikke */
      samiskforvaltningsomraade: boolean;
      /**
       * Format: date-time
       * @description Angir når denne kommunen ble sist oppdatert
       */
      oppdateringsdato: string;
      features: components["schemas"]["FeatureCollection"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description En referanse til et fylke */
    EksternFylkeRef: {
      id: components["schemas"]["ObjektIdentifikator"];
      /** @description Liste over navn til fylket */
      navn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description URL til full representasjon av fylket */
      href: string;
      fylkesnummer: components["schemas"]["Fylkesnummer"];
      /**
       * Format: int32
       * @description Antall publiserte framtidige gyldige versjoner.
       */
      antallFramtidigeVersjoner: number;
    };
    /** @description Representasjon av et fylkesnummer */
    Fylkesnummer: {
      /** @description Unik UUID for fylkesnummeret */
      id: string;
      /** @description Det faktiske fylkesnummeret */
      kodeverdi: string;
    };
    /** @description Representasjon av et fylke */
    EksternFylkeResponse: {
      id: components["schemas"]["ObjektIdentifikator"];
      /** @description Liste over navn til fylket */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      fylkesnummer: components["schemas"]["Fylkesnummer"];
      /** @description Angir om fylket er et samisk forvaltningsområde eller ikke */
      samiskforvaltningsomraade: boolean;
      /**
       * Format: date-time
       * @description Angir når dette fylket ble sist oppdatert
       */
      oppdateringsdato: string;
      features: components["schemas"]["FeatureCollection"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    AuthZStatusResponse: {
      /** @description Status for autorisering */
      authorized: boolean;
    };
  };
}

export interface operations {
  /** Henter utkast med gitt id */
  hentUtkast: {
    parameters: {
      path: {
        /** ID-en til utkastet man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["UtkastResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  /** Oppdaterer angitt utkast. Returnerer oppdatert utkast. */
  oppdaterUtkast: {
    parameters: {
      path: {
        /** ID til utkastet man vil oppdatere */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["UtkastResponse"];
        };
      };
      /** Bad request. Check the request body and path */
      400: {
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** Conflict */
      409: {
        content: {
          "application/json": components["schemas"]["OptimistiskLaasWrapper"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OppdaterUtkastRequest"];
      };
    };
  };
  /** Forkast angitt utkast. */
  forkastUtkast: {
    parameters: {
      path: {
        /** ID til utkastet man vil slette */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: unknown;
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  /** Henter alle utkast i status Opprettet sortert på navn. */
  hentUtkastIStatusOpprettet: {
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["UtkastRef"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  /** Oppretter et utkast og returnerer id. */
  opprettUtkast: {
    responses: {
      /** Successful operation */
      201: {
        content: {
          "application/json": string;
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OpprettUtkastRequest"];
      };
    };
  };
  /** Publiserer utkastet med gitt id. */
  publiserUtkast: {
    parameters: {
      path: {
        /** ID-en til utkastet man vil publisere */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: unknown;
      /** Bad request. Check the request body and path */
      400: {
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** Conflict */
      409: {
        content: {
          "application/json": components["schemas"]["OptimistiskLaasWrapper"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PubliserUtkastRequest"];
      };
    };
  };
  logMelding: {
    responses: {
      /** Successful operation */
      200: unknown;
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FrontendLogRequest"];
      };
    };
  };
  /** Returnerer en liste av nåværende Stemmekrets og eventuelt publiserte framtidige versjoner som matcher lokalid. */
  hentFramtidigeVersjonerForStemmekrets: {
    parameters: {
      path: {
        /** LokalID-en til stemmekretsen man vil hente versjoner for */
        lokalid: string;
      };
      query: {
        /** Eventuell gyldighetsdato for stemmekrets (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["StemmekretsResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  /** Henter stemmekrets med gitt id */
  hentStemmekrets: {
    parameters: {
      path: {
        /** ID-en til stemmekretsen man vil hente */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for stemmekrets (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["StemmekretsResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["StemmekretsResponse"];
        };
      };
    };
  };
  /** Henter grensene til en stemmekrets med gitt id */
  hentGrenserForStemmekrets: {
    parameters: {
      path: {
        /** ID-en til stemmekretsen man vil hente */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for stemmekrets (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  /** Henter nasjon på en gitt dato */
  hentNasjon: {
    parameters: {
      query: {
        /** Eventuell gyldighetsdato for nasjonen (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["NasjonResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["NasjonResponse"];
        };
      };
    };
  };
  /** Henter alle kommuner i Nasjonal inndelingsbase. */
  hentKommuner: {
    parameters: {
      query: {
        /** Valgfri id til et fylke for å filtrere kommuner innenfor et fylke */
        fylkeid?: string;
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["KommuneResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  /** Henter kommune med gitt id */
  hentKommune: {
    parameters: {
      path: {
        /** ID-en til kommunen man vil hente */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["KommuneResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["KommuneResponse"];
        };
      };
    };
  };
  hentKommunesStemmekretsgrenser: {
    parameters: {
      path: {
        /** ID til kommunen man vil hente stemmekretsgrensene til */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  /** Henter alle stemmekretser som tilhører en kommune. */
  hentKommunesStemmekretser: {
    parameters: {
      path: {
        /** ID til kommunen man vil hente stemmekretsene til */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["StemmekretsResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  hentKommunesInndelingerMedDeltGeometriGrenser: {
    parameters: {
      path: {
        /** ID til kommunen man vil hente grensene i inndelingene til */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  hentKommunesInndelingerMedDeltGeometri: {
    parameters: {
      path: {
        /** ID til kommunen man vil hente inndelingene til */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["InndelingResponse"][];
        };
      };
    };
  };
  hentKommunesGrunnkretsgrenser: {
    parameters: {
      path: {
        /** ID til kommunen man vil hente grunnkretsgrensene til */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  /** Henter alle grunnkretser som tilhører en kommune. */
  hentKommunesGrunnkretser: {
    parameters: {
      path: {
        /** ID til kommunen man vil hente grunnkretsene til */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["GrunnkretsResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  /** Henter grensene til en kommune med gitt id */
  hentGrenserForKommune: {
    parameters: {
      path: {
        /** ID-en til kommunen man vil hente */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  fetchMaalemetodeKoder: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["KodelisteRespons"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  /** Søk etter inndelinger ved å bruke en søkestring */
  finnInndelinger: {
    parameters: {
      query: {
        /** Søkestring for å finne inndelinger */
        searchString: string;
        /** Eventuell gyldighetsdato for inndelingene (default = dagens dato) */
        gyldighetsdato?: string;
        /** Maksgrense for antall treff man ønsker seg */
        limit?: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["InndelingSearchResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["InndelingSearchResponse"][];
        };
      };
    };
  };
  /** Returnerer en liste av nåværende Grunnkrets og eventuelt publiserte framtidige versjoner som matcher lokalid. */
  hentFramtidigeVersjonerForGrunnkrets: {
    parameters: {
      path: {
        /** LokalID-en til grunnkretsen man vil hente versjoner for */
        lokalid: string;
      };
      query: {
        /** Eventuell gyldighetsdato for grunnkrets (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["GrunnkretsResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  /** Henter grunnkrets med gitt id */
  hentGrunnkrets: {
    parameters: {
      path: {
        /** ID-en til grunnkretsen man vil hente */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for grunnkrets (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["GrunnkretsResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["GrunnkretsResponse"];
        };
      };
    };
  };
  /** Henter grensene til en grunnkrets med gitt id */
  hentGrenserForGrunnkrets: {
    parameters: {
      path: {
        /** ID-en til grunnkretsen man vil hente */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for grunnkrets (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  /** Henter alle fylker i Nasjonal inndelingsbase. */
  hentFylker: {
    parameters: {
      query: {
        /** Eventuell gyldighetsdato for fylkene (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FylkeResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  /** Henter fylke med gitt id */
  hentFylke: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for fylke (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FylkeResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FylkeResponse"];
        };
      };
    };
  };
  hentFylkesStemmekretser: {
    parameters: {
      path: {
        /** ID til fylket man vil hente stemmekretsenee til */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for fylket (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["StemmekretsResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  hentFylkesGrunnkretser: {
    parameters: {
      path: {
        /** ID til fylket man vil hente grunnkretsene til */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for fylket (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["GrunnkretsResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  /** Henter grensene til et fylke med gitt id */
  hentGrenserForFylke: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for fylke (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  /** Henter stemmekretser med gitte id-er */
  hentStemmekretserForIds: {
    parameters: {
      query: {
        /** ID-ene til stemmekretsene man vil hente */
        ids: string[];
        /** Eventuell gyldighetsdato for stemmekrets (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["EksternKretsResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["EksternKretsResponse"][];
        };
      };
    };
  };
  /** Henter stemmekrets med gitt id */
  hentStemmekrets_1: {
    parameters: {
      path: {
        /** ID-en til stemmekretsen man vil hente */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for stemmekrets (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["EksternStemmekretsResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["EksternStemmekretsResponse"];
        };
      };
    };
  };
  /** Henter grensene til en stemmekrets med gitt id */
  hentGrenserForStemmekrets_1: {
    parameters: {
      path: {
        /** ID-en til stemmekretsen man vil hente */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for stemmekrets (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  /** Henter alle kommuner i Nasjonal inndelingsbase. */
  hentKommuner_1: {
    parameters: {
      query: {
        /** Valgfri id til et fylke for å filtrere kommuner innenfor et fylke */
        fylkeid?: string;
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["EksternKommuneRef"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  /** Henter alle stemmekretser med detaljer for gitt kommunenummer. Denne brukes for uthenting av data til dataplattform. */
  hentAlleStemmekretserMedDetaljerForKommune: {
    parameters: {
      path: {
        /** Kommunenummer for kommune man ønsker å hente stemmekretsene til */
        kommunenummer: string;
      };
      query: {
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["EksternKretsResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["EksternStemmekretsResponse"][];
        };
      };
    };
  };
  /** Henter alle stemmekretser for gitt kommunenummer */
  hentAlleStemmekretserForKommune: {
    parameters: {
      path: {
        /** Kommunenummer for kommune man ønsker å hente stemmekretsene til */
        kommunenummer: string;
      };
      query: {
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["EksternKretsResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["EksternKretsResponse"][];
        };
      };
    };
  };
  /** Henter alle grunnkretser med detaljer for gitt kommunenummer. Denne brukes for uthenting av data til dataplattform. */
  hentAlleGrunnkretserMedDetaljerForKommune: {
    parameters: {
      path: {
        /** Kommunenummer for kommune man ønsker å hente grunnkretsene til */
        kommunenummer: string;
      };
      query: {
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["EksternKretsResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["EksternGrunnkretsResponse"][];
        };
      };
    };
  };
  /** Henter alle grunnkretser for gitt kommunenummer */
  hentAlleGrunnkretserForKommune: {
    parameters: {
      path: {
        /** Kommunenummer for kommune man ønsker å hente grunnkretsene til */
        kommunenummer: string;
      };
      query: {
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["EksternKretsResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["EksternKretsResponse"][];
        };
      };
    };
  };
  /** Henter kommune med gitt id */
  hentKommune_1: {
    parameters: {
      path: {
        /** ID-en til kommunen man vil hente */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for kommune (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["EksternKommuneResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["EksternKommuneResponse"];
        };
      };
    };
  };
  /** Henter grunnkretser med gitte id-er */
  hentGrunnkretserForIds: {
    parameters: {
      query: {
        /** ID-ene til grunnkretsene man vil hente */
        ids: string[];
        /** Eventuell gyldighetsdato for grunnkrets (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["EksternKretsResponse"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["EksternKretsResponse"][];
        };
      };
    };
  };
  /** Henter grensene til en grunnkrets med gitt id */
  hentGrenserForGrunnkrets_1: {
    parameters: {
      path: {
        /** ID-en til grunnkretsen man vil hente */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for grunnkrets (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  /** Henter alle fylker i Nasjonal inndelingsbase. */
  hentFylker_1: {
    parameters: {
      query: {
        /** Eventuell gyldighetsdato for fylkene (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["EksternFylkeRef"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
    };
  };
  /** Henter fylke med gitt id */
  hentFylke_1: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
      };
      query: {
        /** Eventuell gyldighetsdato for fylke (default = dagens dato */
        gyldighetsdato?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["EksternFylkeResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["EksternFylkeResponse"];
        };
      };
    };
  };
  /** Henter status for autorisering */
  getStatus: {
    responses: {
      /** Bruker er autorisert */
      200: {
        content: {
          "application/json": components["schemas"]["AuthZStatusResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Bruker er ikke autorisert */
      403: {
        content: {
          "application/json": components["schemas"]["AuthZStatusResponse"];
        };
      };
    };
  };
}

export interface external {}
