/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/avvik": {
    /** Henter alle registrerte avvik mellom administrative grenser i NIBAS og Matrikkelen */
    get: operations["hentAlleAvvik"];
    /** Oppdaterer flere avvik samtidig med ny status og informasjon */
    post: operations["oppdaterFlereAvvik"];
  };
  "/api/v1/matrikkel/grenselinjer": {
    /** Henter alle grenselinjer for en kommuner fra Matrikkelen. */
    get: operations["hentGrenselinjer"];
  };
  "/api/v1/matrikkel/grenselinjer/kommuner": {
    /** Henter en liste over alle kommuner som har tilgjengelige grenselinjer */
    get: operations["hentTilgjengeligeKommuner"];
  };
  "/api/v1/avvik/kommuner": {
    /** Henter liste over kommuner med avvik og antall avvik per kommune */
    get: operations["hentKommunerMedAvvikSummary"];
  };
  "/api/v1/avvik/kommune/{lokalId}": {
    /** Henter alle registrerte avvik mellom administrative grenser i NIBAS og Matrikkelen for en gitt kommune */
    get: operations["hentAvvik"];
  };
}

export interface components {
  schemas: {
    AvvikRequestDTO: {
      /** Format: int64 */
      id: number;
      /** @enum {string} */
      status: "NY" | "UNDER_BEHANDLING" | "FIKSET" | "VENT" | "AVVIST";
    };
    BulkAvvikRequestDTO: {
      avvikUpdates: components["schemas"]["AvvikRequestDTO"][];
    };
    GeometryDto: {
      type: string;
      coordinates: number[][];
    };
    MatrikkelGrenselinjeDto: {
      type: string;
      geometry: components["schemas"]["GeometryDto"];
      properties: components["schemas"]["PropertiesDto"];
    };
    MatrikkelGrenselinjeFeatureCollection: {
      type: string;
      features: components["schemas"]["MatrikkelGrenselinjeDto"][];
    };
    PropertiesDto: {
      /** Format: int64 */
      id: number;
      kommunenr1?: string;
      kommunenr2?: string;
      /** Format: int32 */
      hjelpelinjetypeId?: number;
      /** Format: int32 */
      administrativgrensekodeId?: number;
      /** Format: int32 */
      malemetodeId?: number;
      /** Format: int32 */
      noyaktighet?: number;
      /** Format: int32 */
      lagretNoyaktighetsklasse?: number;
    };
    Page: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: unknown[];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components["schemas"]["PageableObject"];
      empty?: boolean;
    };
    PageableObject: {
      /** Format: int64 */
      offset?: number;
      sort?: components["schemas"]["SortObject"];
      paged?: boolean;
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      pageSize?: number;
      unpaged?: boolean;
    };
    SortObject: {
      empty?: boolean;
      sorted?: boolean;
      unsorted?: boolean;
    };
    KommuneAvvikDTO: {
      fylkesLokalID?: string;
      kommuneLokalID?: string;
      kommuneNummer: string;
      kommuneNavn: string;
      /** Format: int32 */
      antallAvvik: number;
    };
  };
}

export interface operations {
  /** Henter alle registrerte avvik mellom administrative grenser i NIBAS og Matrikkelen */
  hentAlleAvvik: {
    parameters: {
      query: {
        grensetyper?: string[];
        side?: number;
        antall?: number;
      };
    };
    responses: {
      /** Vellykket operasjon */
      200: {
        content: {
          "application/json": components["schemas"]["Page"];
        };
      };
      /** Serverfeil */
      500: unknown;
    };
  };
  /** Oppdaterer flere avvik samtidig med ny status og informasjon */
  oppdaterFlereAvvik: {
    responses: {
      /** Vellykket operasjon */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** Ugyldig forespørsel */
      400: unknown;
      /** Avvik ikke funnet */
      404: unknown;
      /** Serverfeil */
      500: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkAvvikRequestDTO"];
      };
    };
  };
  /** Henter alle grenselinjer for en kommuner fra Matrikkelen. */
  hentGrenselinjer: {
    parameters: {
      query: {
        kommunenummer?: string;
      };
    };
    responses: {
      /** Grenselinjene ble funnet */
      200: {
        content: {
          "application/geo+json": components["schemas"]["MatrikkelGrenselinjeFeatureCollection"];
        };
      };
      /** Ugyldig forespørsel */
      400: unknown;
      /** Ingen grenselinjer funnet for kommunen */
      404: unknown;
    };
  };
  /** Henter en liste over alle kommuner som har tilgjengelige grenselinjer */
  hentTilgjengeligeKommuner: {
    responses: {
      /** Liste over tilgjengelige kommuner */
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
  /** Henter liste over kommuner med avvik og antall avvik per kommune */
  hentKommunerMedAvvikSummary: {
    parameters: {
      query: {
        grensetyper?: string[];
        side?: number;
        antall?: number;
      };
    };
    responses: {
      /** Vellykket operasjon */
      200: {
        content: {
          "application/json": components["schemas"]["KommuneAvvikDTO"];
        };
      };
      /** Serverfeil */
      500: unknown;
    };
  };
  /** Henter alle registrerte avvik mellom administrative grenser i NIBAS og Matrikkelen for en gitt kommune */
  hentAvvik: {
    parameters: {
      path: {
        lokalId: string;
      };
      query: {
        grensetyper?: string[];
      };
    };
    responses: {
      /** Vellykket operasjon */
      200: {
        content: {
          "application/json": components["schemas"]["Page"];
        };
      };
      /** Serverfeil */
      500: unknown;
    };
  };
}
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface external {}
