/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/utkast/{id}": {
    /** Henter utkast med gitt id */
    get: operations["hentUtkast"];
    /** Oppdaterer angitt utkast. Returnerer oppdatert utkast. */
    put: operations["oppdaterUtkast"];
  };
  "/v1/admin/kodelister/invalidate": {
    /** Invaliderer kodeliste-cache slik at kodelister refreshes. */
    put: operations["invalidateKodelisteCache"];
  };
  "/v1/utkast": {
    /** Oppretter et utkast og returnerer id. */
    post: operations["opprettUtkast"];
  };
  "/v1/utkast/{id}/publiser": {
    /** Publiserer utkastet med gitt id. */
    post: operations["publiserUtkast"];
  };
  "/v1/stemmekretser/{id}": {
    /** Henter stemmekrets med gitt id */
    get: operations["hentStemmekrets"];
  };
  "/v1/stemmekretser/{id}/revisjoner": {
    /** Henter historiske revisjoner til en stemmekrets med gitt id */
    get: operations["hentStemmekretsRevisjoner"];
  };
  "/v1/stemmekretser/{id}/revisjoner/{revisjon}": {
    /** Henter en gitt historisk revisjon av en stemmekrets */
    get: operations["hentStemmekretsRevisjon"];
  };
  "/v1/stemmekretser/{id}/grenser": {
    /** Henter grensene til en stemmekrets med gitt id */
    get: operations["hentGrenserForStemmekrets"];
  };
  "/v1/nasjoner": {
    /** Henter alle nasjoner i Nasjonal inndelingsbase. */
    get: operations["hentNasjoner"];
  };
  "/v1/nasjoner/{id}": {
    /** Henter nasjon med gitt id */
    get: operations["hentNasjon"];
  };
  "/v1/nasjoner/{id}/revisjoner": {
    /** Henter historiske revisjoner til en nasjon med gitt id */
    get: operations["hentNasjonRevisjoner"];
  };
  "/v1/nasjoner/{id}/revisjoner/{revisjon}": {
    /** Henter en gitt historisk revisjon av en nasjon */
    get: operations["hentNasjonRevisjon"];
  };
  "/v1/nasjoner/{id}/grenser": {
    /** Henter grensene til en nasjon med gitt id */
    get: operations["hentGrenserForNasjon"];
  };
  "/v1/kommuner": {
    /** Henter alle kommuner i Nasjonal inndelingsbase. */
    get: operations["hentKommuner"];
  };
  "/v1/kommuner/{id}": {
    /** Henter kommune med gitt id */
    get: operations["hentKommune"];
  };
  "/v1/kommuner/{id}/stemmekretser": {
    get: operations["hentKommunesStemmekretser"];
  };
  "/v1/kommuner/{id}/revisjoner": {
    /** Henter historiske revisjoner til en kommune med gitt id */
    get: operations["hentKommuneRevisjoner"];
  };
  "/v1/kommuner/{id}/revisjoner/{revisjon}": {
    /** Henter en gitt historisk revisjon av en kommune */
    get: operations["hentKommuneRevisjon"];
  };
  "/v1/kommuner/{id}/grunnkretser": {
    /** Henter alle grunnkretser som tilhører en kommune. */
    get: operations["hentKommunesGrunnkretser"];
  };
  "/v1/kommuner/{id}/grenser": {
    /** Henter grensene til en kommune med gitt id */
    get: operations["hentGrenserForKommune"];
  };
  "/v1/kodeliste/terrengdetaljkoder": {
    get: operations["fetchTerrengdetaljkoder"];
  };
  "/v1/kodeliste/noeyaktighetsklasser": {
    get: operations["fetchNoeyaktighetsklasser"];
  };
  "/v1/kodeliste/maalemetode-koder": {
    get: operations["fetchMaalemetodeKoder"];
  };
  "/v1/kodeliste/landkoder": {
    get: operations["fetchLandkoder"];
  };
  "/v1/kodeliste/kommunenumre": {
    get: operations["fetchKommunenumre"];
  };
  "/v1/kodeliste/grensetyper": {
    get: operations["fetchGrensetyper"];
  };
  "/v1/kodeliste/grensestatuser": {
    get: operations["fetchGrensestatuskoder"];
  };
  "/v1/kodeliste/fylkesnumre": {
    get: operations["fetchFylkesnumre"];
  };
  "/v1/kodeliste/fastsettingstyper": {
    get: operations["fetchFastsettingstyper"];
  };
  "/v1/grunnkretser/{id}": {
    /** Henter grunnkrets med gitt id */
    get: operations["hentGrunnkrets"];
  };
  "/v1/grunnkretser/{id}/revisjoner": {
    /** Henter historiske revisjoner til en grunnkrets med gitt id */
    get: operations["hentGrunnkretsRevisjoner"];
  };
  "/v1/grunnkretser/{id}/revisjoner/{revisjon}": {
    /** Henter en gitt historisk revisjon av en grunnkrets */
    get: operations["hentGrunnkretsRevisjon"];
  };
  "/v1/grunnkretser/{id}/grenser": {
    /** Henter grensene til en grunnkrets med gitt id */
    get: operations["hentGrenserForGrunnkrets"];
  };
  "/v1/grenser/{id}": {
    /** Henter grense med gitt id */
    get: operations["hentGrense"];
  };
  "/v1/grenser/{id}/revisjoner": {
    /** Henter historiske revisjoner for grense med gitt id */
    get: operations["hentGrenseRevisjoner"];
  };
  "/v1/grenser/{id}/revisjoner/{revisjon}": {
    /** Henter gitt historisk revisjon for gitt grense */
    get: operations["hentGrenseRevisjon"];
  };
  "/v1/fylker": {
    /** Henter alle fylker i Nasjonal inndelingsbase. */
    get: operations["hentFylker"];
  };
  "/v1/fylker/{id}": {
    /** Henter fylke med gitt id */
    get: operations["hentFylke"];
  };
  "/v1/fylker/{id}/revisjoner": {
    /** Henter historiske revisjoner til et fylke med gitt id */
    get: operations["hentFylkesRevisjoner"];
  };
  "/v1/fylker/{id}/revisjoner/{revisjon}": {
    /** Henter en gitt historisk revisjon av et fylke */
    get: operations["hentFylkesRevisjon"];
  };
  "/v1/fylker/{id}/grenser": {
    /** Henter grensene til et fylke med gitt id */
    get: operations["hentGrenserForFylke"];
  };
  "/v1/ekstern/matrikkel/stemmekretser": {
    /** Henter stemmekretser med gitte id-er */
    get: operations["hentStemmekretserForIds"];
  };
  "/v1/ekstern/matrikkel/kommuner/{kommunenummer}/stemmekretser": {
    /** Henter alle stemmekretser for gitt kommunenummer */
    get: operations["hentAlleStemmekretserForKommune"];
  };
  "/v1/ekstern/matrikkel/kommuner/{kommunenummer}/grunnkretser": {
    /** Henter alle grunnkretser for gitt kommunenummer */
    get: operations["hentAlleGrunnkretserForKommune"];
  };
  "/v1/ekstern/matrikkel/grunnkretser": {
    /** Henter grunnkretser med gitte id-er */
    get: operations["hentGrunnkretserForIds"];
  };
}

export interface components {
  schemas: {
    /** @description Representasjon av et navn */
    AdministrativEnhetNavn: {
      /** @description Navnet på en administrativ enhet */
      navn: string;
      /** @description Språkkoden til det administrative navnet */
      spraak: string;
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Spesfikk metadata for en administrativ grense (fylkes/kommunegrense). Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Objekttype/Index/EAID_5142EDBA_4226_4ca3_924D_EECEFD216D1A */
    AdministrativGrenseMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      /** @description Henviser til fastsettings- eller lovinformasjon. */
      dokumentasjonsreferanser?: components["schemas"]["Dokref"][];
      foelgerTerrengdetalj?: components["schemas"]["KodelisteEntry"];
      noeyaktighetsklasse?: components["schemas"]["KodelisteEntry"];
      /** @description Angir om grensen er omtvistet, eller det er tvil om forløpet. */
      omtvistet?: boolean;
    } & {
      common: unknown;
      commonGrense: unknown;
      dokumentasjonsreferanser: unknown;
      foelgerTerrengdetalj: unknown;
      noeyaktighetsklasse: unknown;
    };
    /** @description Spesifikk metadata for en AvtaltAvgrensningslinje. Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Diagram/Index/EAID_EEECEE48_B3FA_4807_AAE4_B30B63BC28E1 */
    AvtaltAvgrensningslinjeMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      /** @description Henviser til fastsettings- eller lovinformasjon. */
      dokumentasjonsreferanser?: components["schemas"]["Dokref"][];
      maritimeGrenser?: components["schemas"]["MaritimeGrenserMetadata"];
    } & {
      common: unknown;
      commonGrense: unknown;
      dokumentasjonsreferanser: unknown;
      maritimeGrenser: unknown;
    };
    /** @description Felles metadata-egenskaper for grenser. */
    CommonGrenseMetadata: {
      posisjonskvalitet?: components["schemas"]["Posisjonskvalitet"];
      grensestatus: components["schemas"]["KodelisteEntry"];
      fastsettingstype: components["schemas"]["KodelisteEntry"];
    };
    /** @description Felles metadata-egenskaper. */
    CommonMetadata: {
      identifikasjon: components["schemas"]["Identifikasjon"];
      /**
       * Format: date
       * @description Dato når objektet siste gang ble registrert/observert/målt i terrenget
       */
      datafangstdato?: string;
      /**
       * Format: date
       * @description Tidspunktet når objektet oppstod i den virkelige verden
       */
      gyldigFra: string;
      /**
       * Format: date
       * @description Tidspunktet når objektet opphørte å eksistere i den virkelige verden
       */
      gyldigTil?: string;
      /** @description Generelle opplysninger/merknad */
      informasjon?: string;
      sporingsinformasjon: components["schemas"]["Sporingsinformasjon"];
      /** @description Referanse til opphavsmaterialet, kildematerialet, organisasjons/publiseringskilde. */
      opphav?: string;
    };
    /** @description Henviser til fastsettings- eller lovinformasjon. */
    Dokref: {
      /** @description ID for dokumentasjonsreferansen. */
      id?: string;
      /** @description URL til saksdokument. */
      dokumentlenker: components["schemas"]["TekstHolder"][];
      /**
       * Format: date
       * @description Dato for når dokumentet ble skrevet, publisert eller revidert.
       */
      fastsettingsdato: string;
      /** @description Offentlig instans som har fastsatt en grense. */
      fastsettingsmyndighet?: string;
      /** @description Lov som rettskilden er begrunnet i. */
      hjemmel?: string;
      /** @description Henvisning til saksdokument i Kartverkets eget arkiv. */
      internReferanserKartverket: components["schemas"]["TekstHolder"][];
      /** @description Referanse til lov, forskrift, vedtak, dom eller traktat i form av kode som angir type dokument, dato og nummer For eksempel: LOV-2012-09-07-65. */
      rettskildeId?: string;
      /** @description Navn på lov, forskrift, vedtak, dom eller traktat. */
      rettskildeTittel: string;
    };
    /** @description Liste av features som holder på dataene */
    Feature: {
      /** @description En konstant, navn: type, verdi: Feature */
      type: string;
      /** @description Id til feature */
      id?: string;
      properties: components["schemas"]["FeatureProperties"];
      geometry: components["schemas"]["Geometry"];
    };
    /** @description Egenskaper som beskriver en gitt feature (properties-objektet i geojson-strukturen) */
    FeatureProperties: {
      /** @description Avhengig av hva slags feature man har kan dette være enten grensetype eller geometri-type (posisjon eller flate) */
      type: string;
      /**
       * Format: int32
       * @description Koordinatsystemet. Defaulter til 25833.
       */
      srid: number;
      metadata?: components["schemas"]["Metadata"];
      kontekstEgenskaper?: components["schemas"]["KontekstEgenskaper"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Metadata for en flate (felles for nasjon, fylke, kommune og grunnkrets) */
    FlateMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
    } & {
      common: unknown;
    };
    /** @description Endringer på fylke. */
    FylkeRequest: {
      /** @description Navnene til fylket */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalId for angitt fylke */
      lokalid: string;
      /** @description Navnerommet for fylket */
      navnerom: string;
      /** @description UUID til fylkesnummeret */
      fylkesnummerId: string;
      /** @description Angir om fylket er et samisk forvaltningsområde */
      samiskforvaltningsomraade: boolean;
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Geometry-typene vi støtter i NIBAS. */
    Geometry: {
      type: string;
    };
    /** @description Representasjon av endringer på grensegeometri. */
    Grenseendringer: {
      /** @description Endringer på features. */
      endredeFeatures?: { [key: string]: components["schemas"]["Feature"] };
    };
    /** @description Representasjon av en grunnkrets */
    GrunnkretsRequest: {
      /** @description Navnet på grunnkretsen */
      navn: string;
      /** @description Grunnkretsnummeret til grunnkretsen */
      grunnkretsnummer: string;
      identifikasjon: components["schemas"]["Identifikasjon"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Spesifikk metadata for en Grunnlinje. Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Diagram/Index/EAID_EEECEE48_B3FA_4807_AAE4_B30B63BC28E1 */
    GrunnlinjeMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      /** @description Henviser til fastsettings- eller lovinformasjon. */
      dokumentasjonsreferanser?: components["schemas"]["Dokref"][];
      maritimeGrenser?: components["schemas"]["MaritimeGrenserMetadata"];
      kommunenummer?: components["schemas"]["Kommunenummer"];
    } & {
      common: unknown;
      commonGrense: unknown;
      dokumentasjonsreferanser: unknown;
      maritimeGrenser: unknown;
    };
    /** @description Angir om grensen følger grunnkretsgrense og i så fall hvilken grunnkretsgrense */
    Identifikasjon: {
      /** @description Lokal id som identifiserer geometrien. Dette er en globalt unik id. */
      lokalid: string;
      /** @description Navnerom som unikt identifiserer datakilden til objektet, starter med to bokstavs kode jfr ISO 3166. */
      navnerom: string;
      /** @description Identifikasjon av en spesiell versjon av et geografisk objekt (instans), maksimum lengde på 25 karakterer. */
      versjonid?: string;
    };
    /** @description Klassifikasjon av stedfestingsnøyaktighet på grenser, og er basert på dårligste nøyaktighet til grensepunktene til grensen. */
    KodelisteEntry: {
      /** @description Id for kodeliste-innslaget. */
      id?: string;
      /** @description Lenke til kodelista. */
      href: string;
    };
    /** @description Representasjon av en kommune */
    KommuneRequest: {
      /** @description Navnene til kommunen */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalId for angitt kommune */
      lokalid: string;
      /** @description Navnerommet for kommunen */
      navnerom?: string;
      /** @description UUID til kommunenummeret */
      kommunenummerId: string;
      /** @description Angir om kommunen er et samisk forvaltningsområde */
      samiskforvaltningsomraade: boolean;
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Representasjon av et kommunenummer */
    Kommunenummer: {
      /** @description Unik UUID for kommunenummeret */
      id: string;
      /**
       * Format: int32
       * @description Det faktiske kommunenummeret
       */
      kodeverdi?: number;
    };
    /** @description Egenskaper som beskriver konteksten som grensen sees i. */
    KontekstEgenskaper: {
      /** @description Id til objekt som det vises til i kontekst */
      id?: string;
      /**
       * @description Hvilken kontekst geometrien skal sees i
       * @enum {string}
       */
      type?: "GRUNNKRETS" | "STEMMEKRETS";
      /** @description Angir om grensen skal leses med klokken for å danne flate. */
      retningMedKlokken: boolean;
      /**
       * Format: int32
       * @description Angir rekkefølgen på gitt grenselinje i flatedanningen.
       */
      rekkefoelge: number;
      /**
       * Format: int32
       * @description Angir hvilken flate for enheten grensen er en del av.
       */
      flateIndeks: number;
      /**
       * Format: int32
       * @description Angir om grensen er en del av et hull, og i så fall index på gitt hull.
       */
      hullIndeks?: number;
    };
    /** @description Angivelse av hvilke land grensa er knyttet til Merknad: Alfanumerisk kode (ISO 3166-1 alpha-2) for land som definert i ISO 3166. */
    Landkoder: {
      /** @description Liste av valgte landkode-ids. */
      ids: string[];
      /** @description Peker til landkoder-kodeliste. */
      href: string;
    };
    /** @description Wrapper-objekt rundt en JTS LineString. */
    LineString: components["schemas"]["Geometry"] & {
      /** @description Geometriens type. Diskriminator. */
      type?: string;
      /** @description Liste av (x og y som liste). */
      coordinates?: number[][];
    } & {
      coordinates: unknown;
      type: unknown;
    };
    /** @description Metadata-egenskaper for maritim grense. */
    MaritimeGrenserMetadata: {
      /** @description Organisasjon som er ansvarlig for opprettholdelse av grensa. */
      ansvarligeMyndigheter: components["schemas"]["TekstHolder"][];
      /** @description Navn på område som loven gjelder for, eller område som grensa er beregnet fra. */
      gjelderOmraade?: string;
      /**
       * Format: date
       * @description Tidspunktet for når koordinatene er transformert fra originalt koordinatsystem.
       */
      transformasjonsdato?: string;
      /** @description Begrep knyttet til yttergrensa for virkeområdet, som oftest angitt i lov eller forskrift. */
      virkeomraadenavn?: string;
      land: components["schemas"]["Landkoder"];
    };
    /** @description Diverse metadata-felter fra sosi-modellen. */
    Metadata: {
      discriminator: string;
    };
    /** @description Representasjon av endringer på metadata. */
    Metadataendringer: {
      /** @description Endringer på nasjon. */
      nasjonsendringer?: {
        [key: string]: components["schemas"]["NasjonRequest"];
      };
      /** @description Endringer på fylke. */
      fylkesendringer?: {
        [key: string]: components["schemas"]["FylkeRequest"];
      };
      /** @description Endringer på kommune. */
      kommuneendringer?: {
        [key: string]: components["schemas"]["KommuneRequest"];
      };
      /** @description Endringer på grunnkrets. */
      grunnkretsendringer?: {
        [key: string]: components["schemas"]["GrunnkretsRequest"];
      };
      /** @description Endringer på stemmekrets. */
      stemmekretsendringer?: {
        [key: string]: components["schemas"]["StemmekretsRequest"];
      };
    };
    /** @description Wrapper-objekt rundt et JTS MultiPolygon. */
    MultiPolygon: components["schemas"]["Geometry"] & {
      /** @description Geometriens type. Diskriminator. */
      type?: string;
      /** @description Liste av polygonenes liste av LinearRings som igjen har liste av koordinater som er liste av x og y. */
      coordinates?: number[][][][];
    } & {
      coordinates: unknown;
      type: unknown;
    };
    /** @description Endringer på nasjon. */
    NasjonRequest: {
      /** @description Navnene til nasjonen */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalId for angitt nasjon */
      lokalid: string;
      /** @description Navnerommet for nasjonen */
      navnerom: string;
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Representasjon av operasjoner/handlinger som er utført i klienten. */
    Operasjoner: {
      metadataendringer?: components["schemas"]["Metadataendringer"];
      grenseendringer?: components["schemas"]["Grenseendringer"];
    };
    /** @description Wrapper-objekt rundt en JTS Point. */
    Point: components["schemas"]["Geometry"] & {
      /** @description Geometriens type. Diskriminator. */
      type?: string;
      /** @description X og y som liste. */
      coordinates?: number[];
    } & {
      coordinates: unknown;
      type: unknown;
    };
    /** @description Beskrivelse av kvaliteten på stedfestingen */
    Posisjonskvalitet: {
      maalemetode: components["schemas"]["KodelisteEntry"];
      /**
       * Format: int32
       * @description Punktstandardavviket i grunnriss for punkter samt tverravvik for linjer. Merknad: Oppgitt i cm.
       */
      noeyaktighet?: number;
    };
    /** @description Spesifikk metadata for en riksgrense. Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Objekttype/Index/EAID_5C4B9E4D_05D7_4b2e_B467_9FCA428994F9 */
    RiksgrenseMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      /** @description Henviser til fastsettings- eller lovinformasjon. */
      dokumentasjonsreferanser?: components["schemas"]["Dokref"][];
      foelgerTerrengdetalj?: components["schemas"]["KodelisteEntry"];
      /** @description Angivelse om stedfestingen (koordinatene) er kontrollert og funnet i orden (verifisert). */
      stedfestingVerifisert?: boolean;
      /** @description Organisasjon(er) som er ansvarlig for opprettholdelse av grensa. */
      ansvarligeMyndigheter?: components["schemas"]["TekstHolder"][];
      /**
       * Format: double
       * @description Bredde av området på begge sider av riksgrensen som er ryddet for vegetasjon høyere enn 0,5 m.
       */
      grensegateBredde?: number;
    } & {
      ansvarligeMyndigheter: unknown;
      common: unknown;
      commonGrense: unknown;
      dokumentasjonsreferanser: unknown;
      foelgerTerrengdetalj: unknown;
    };
    /** @description Holder på informasjon om endring av objektet. */
    Sporingsinformasjon: {
      /**
       * Format: date
       * @description Dato for siste endring på objektdataene
       */
      oppdateringsdato: string;
      /** @description Angir hvem som endret data på objektet sist. */
      endretAv?: string;
    };
    /** @description Spesifikk metadata for en statistisk grense (grunnkrets/delområde). Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Objekttype/Index/EAID_374BE5B3_5F8B_498a_8F53_9CCA72619C36 */
    StatistiskgrenseMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      foelgerTerrengdetalj?: components["schemas"]["KodelisteEntry"];
      noeyaktighetsklasse?: components["schemas"]["KodelisteEntry"];
    } & {
      common: unknown;
      commonGrense: unknown;
      foelgerTerrengdetalj: unknown;
      noeyaktighetsklasse: unknown;
    };
    /** @description Representasjon av en stemmekrets */
    StemmekretsRequest: {
      /** @description Stemmekretsnummeret til stemmekretsen */
      stemmekretsnummer?: string;
      identifikasjon: components["schemas"]["Identifikasjon"];
      /** @description Stemmekretsnavnet til stemmekretsen */
      stemmekretsnavn?: string;
      /** @description Tellekretsnummeret til stemmekretsen */
      tellekretsnummer?: string;
      /** @description Tellekretsnavnet til stemmekretsen */
      tellekretsnavn?: string;
      /** @description Valgdistriktsnummeret til stemmekretsen */
      valgdistriktsnummer?: string;
      /** @description Kommunenummeret stemmekretsen tilhører til */
      kommunenummer?: string;
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Organisasjon som er ansvarlig for opprettholdelse av grensa. */
    TekstHolder: {
      /** @description ID for elementet. */
      id?: string;
      /** @description Tekstfelt. */
      beskrivelse: string;
    };
    /** @description Spesifikk metadata for en territorialgrense. Beskrevet i SOSI-modellen her: https://objektkatalog.geonorge.no/Diagram/Index/EAID_EEECEE48_B3FA_4807_AAE4_B30B63BC28E1 */
    TerritorialgrenseMetadata: components["schemas"]["Metadata"] & {
      common?: components["schemas"]["CommonMetadata"];
      commonGrense?: components["schemas"]["CommonGrenseMetadata"];
      /** @description Henviser til fastsettings- eller lovinformasjon. */
      dokumentasjonsreferanser?: components["schemas"]["Dokref"][];
      maritimeGrenser?: components["schemas"]["MaritimeGrenserMetadata"];
      /**
       * Format: date
       * @description Tidspunktet for når koordinatene er utregnet.
       */
      beregningsdato?: string;
    } & {
      common: unknown;
      commonGrense: unknown;
      dokumentasjonsreferanser: unknown;
      maritimeGrenser: unknown;
    };
    /** @description Utkastet som ønskes opprettet */
    UtkastRequest: {
      /** @description Arbeidsnavnet til utkastet. */
      navn: string;
      /** @description Typen endring utkastet representerer. */
      endringstype: string;
      /**
       * Format: date
       * @description Tidspunktet utkastet skal være gyldig fra.
       */
      gyldigFra?: string;
      operasjoner: components["schemas"]["Operasjoner"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    ApiErrorResponse: {
      /**
       * @description HttpStatus for responsen.
       * @enum {string}
       */
      httpStatus:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      /** @description Beskrivelse av hva som har gått galt. */
      melding?: string;
    };
    ConflictResponse: {
      /**
       * @description HttpStatus for responsen.
       * @enum {string}
       */
      httpStatus:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      /** @description Identifikatoren til objektet som er utdatert. */
      id: string;
      /** @description Typen til objektet som er utdatert. */
      type: string;
      /**
       * Format: int32
       * @description Versjon som prøves å oppdateres.
       */
      versjon: number;
      /**
       * Format: int32
       * @description Versjon som er gjeldende for objektet nå.
       */
      gjeldendeVersjon: number;
      /** @description Beskrivelse av hva som har gått galt. */
      melding?: string;
    };
    /** @description Representasjon av audit info for et objekt. */
    AuditInfoResponse: {
      /**
       * Format: date
       * @description Da objektet sist ble oppdatert.
       */
      oppdateringsdato: string;
      /** @description Den som sist endret objektet. */
      endretAv: string;
    };
    /** @description Representasjon av utkast */
    UtkastResponse: {
      /** @description Unik uuid for utkastet */
      id: string;
      /** @description Arbeidsnavnet til utkastet. */
      navn: string;
      /** @description Typen endring utkastet representerer. */
      endringstype: string;
      /** @description Status for utkastet. */
      status: string;
      /**
       * Format: date
       * @description Tidspunktet utkastet skal være gyldig fra.
       */
      gyldigFra: string;
      /**
       * Format: date-time
       * @description Da utkastet ble opprettet.
       */
      opprettetDato: string;
      auditInfoResponse: components["schemas"]["AuditInfoResponse"];
      operasjoner: components["schemas"]["Operasjoner"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Geometrien til grunnkretsen, dvs representasjonspunkt og flaten */
    FeatureCollection: {
      /** @description Toppnivå for geojson-strukturen, definert av en konstant med navn type og verdi FeatureCollection */
      type: string;
      /** @description Liste av features som holder på dataene */
      features: components["schemas"]["Feature"][];
    };
    /** @description Representasjon av en stemmekrets */
    StemmekretsResponse: {
      /** @description ID-en til stemmekretsen */
      id: string;
      /** @description Navnet på stemmekretsen */
      stemmekretsnavn: string;
      /** @description Stemmekretsnummeret til stemmekretsen */
      stemmekretsnummer: string;
      identifikasjon: components["schemas"]["Identifikasjon"];
      /** @description Kommunenummeret til stemmekretsen */
      kommunenummer: string;
      /** @description Tellekretsnummer til stemmekretsen */
      tellekretsnummer?: string;
      /** @description Tellekretsnavn til stemmekretsen */
      tellekretsnavn?: string;
      /** @description Valgdistriktsnummer til stemmekretsen */
      valgdistriktsnummer?: string;
      features: components["schemas"]["FeatureCollection"];
    };
    /** @description En referanse til en historisk revisjon av en administrativ enhet */
    RevisjonRef: {
      /**
       * Format: int32
       * @description IDen til den historiske revisjonen
       */
      revisjonId: number;
      /**
       * Format: date-time
       * @description Når revisjonen ble opprettet
       */
      revisjonDato: string;
      /**
       * @description Angir status for hva som medførte en ny revisjon
       * @enum {string}
       */
      revisjonStatus: "NY" | "ENDRET" | "SLETTET";
      /** @description Referanse til hvor den historiske revisjonen kan finnes */
      href: string;
    };
    /** @description En referanse til en nasjon */
    NasjonRef: {
      /** @description ID-en til nasjonen */
      id: string;
      /** @description Liste over navn til nasjonen */
      navn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description URL til full representasjon av nasjonen */
      href: string;
    };
    /** @description Representasjon av en nasjon */
    NasjonResponse: {
      /** @description ID-en til nasjonen */
      id: string;
      /** @description Liste over navn til nasjonen */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalID til nasjonen */
      lokalid: string;
      /** @description Navnerommet til nasjonen */
      navnerom: string;
      features: components["schemas"]["FeatureCollection"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description En referanse til en kommune */
    KommuneRef: {
      /** @description ID-en til kommunen */
      id: string;
      /** @description Liste over navn til kommunen */
      navn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description URL til full representasjon av kommunen */
      href: string;
    };
    KommuneResponse: {
      /** @description ID-en til kommunen */
      id: string;
      /** @description Liste over navn til kommunen */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalIDen til kommunen */
      lokalid: string;
      /** @description Navnerommet til kommunen */
      navnerom: string;
      kommunenummer: components["schemas"]["Kommunenummer"];
      /** @description Angir om kommunen er et samisk forvaltningsområde eller ikke */
      samiskforvaltningsomraade: boolean;
      /**
       * Format: date
       * @description Angir når denne kommunen ble sist oppdatert
       */
      oppdateringsdato: string;
      features: components["schemas"]["FeatureCollection"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description En referanse til en stemmekrets */
    StemmekretsRef: {
      /** @description ID-en til stemmekretsen */
      id: string;
      /** @description Navnet på stemmekretsen */
      navn: string;
      /** @description URL til full representasjon av stemmekrets */
      href: string;
    };
    /** @description En referanse til en grunnkrets */
    GrunnkretsRef: {
      /** @description ID-en til grunnkretser */
      id: string;
      /** @description Navnet på grunnkretser */
      navn: string;
      /** @description URL til full representasjon av grunnkretsen */
      href: string;
      /** @description Nummeret til grunnkretsen */
      grunnkretsnummer: string;
    };
    /** @description Liste av kodeliste-elementer. */
    KodelisteItem: {
      /** @description Id til kodeliste-innslaget. */
      id: string;
      /** @description Beskrivelse av kodeliste-innslaget. */
      label: string;
    };
    KodelisteRespons: {
      /**
       * @description Angir typen av kodeliste.
       * @enum {string}
       */
      type:
        | "KOMMUNENUMMER"
        | "FYLKESNUMMER"
        | "MAALEMETODE_KODE"
        | "LAND"
        | "TERRENGDETALJ"
        | "NOEYAKTIGHETSKLASSE"
        | "GRENSETYPE"
        | "FASTSETTINGSTYPE"
        | "GRENSESTATUS";
      /** @description Liste av kodeliste-elementer. */
      items: components["schemas"]["KodelisteItem"][];
    };
    /** @description Representasjon av en grunnkrets */
    GrunnkretsResponse: {
      /** @description ID-en til grunnkretsen */
      id: string;
      /** @description Navnet på grunnkretsen */
      navn: string;
      /** @description Grunnkretsnummeret til grunnkretsen */
      grunnkretsnummer: string;
      identifikasjon: components["schemas"]["Identifikasjon"];
      /** @description Kommunenummeret til grunnkretsen */
      kommunenummer: string;
      features: components["schemas"]["FeatureCollection"];
    };
    /** @description En referanse til et fylke */
    FylkeRef: {
      /** @description ID-en til fylket */
      id: string;
      /** @description Liste over navn til fylket */
      navn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description URL til full representasjon av fylket */
      href: string;
    };
    /** @description Representasjon av et fylke */
    FylkeResponse: {
      /** @description ID-en til fylket */
      id: string;
      /** @description Liste over navn til fylket */
      administrativenhetnavn: components["schemas"]["AdministrativEnhetNavn"][];
      /** @description LokalIDen til fylket */
      lokalid: string;
      /** @description Navnerommet til fylket */
      navnerom: string;
      fylkesnummer: components["schemas"]["Fylkesnummer"];
      /** @description Angir om fylket er et samisk forvaltningsområde eller ikke */
      samiskforvaltningsomraade: boolean;
      /**
       * Format: date
       * @description Angir når dette fylket ble sist oppdatert
       */
      oppdateringsdato: string;
      features: components["schemas"]["FeatureCollection"];
      /**
       * Format: int32
       * @description Teknisk versjon for å støtte samhandling og redigering
       */
      version: number;
    };
    /** @description Representasjon av et fylkesnummer */
    Fylkesnummer: {
      /** @description Unik UUID for fylkesnummeret */
      id: string;
      /**
       * Format: int32
       * @description Det faktiske fylkesnummeret
       */
      kodeverdi: number;
    };
  };
}

export interface operations {
  /** Henter utkast med gitt id */
  hentUtkast: {
    parameters: {
      path: {
        /** ID-en til utkastet man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["UtkastResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  /** Oppdaterer angitt utkast. Returnerer oppdatert utkast. */
  oppdaterUtkast: {
    parameters: {
      path: {
        /** ID til utkastet man vil oppdatere */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["UtkastResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** Conflict */
      409: {
        content: {
          "application/json": components["schemas"]["ConflictResponse"][];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UtkastRequest"];
      };
    };
  };
  /** Invaliderer kodeliste-cache slik at kodelister refreshes. */
  invalidateKodelisteCache: {
    responses: {
      /** Successful operation */
      200: unknown;
    };
  };
  /** Oppretter et utkast og returnerer id. */
  opprettUtkast: {
    responses: {
      /** Successful operation */
      201: {
        content: {
          "application/json": string;
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UtkastRequest"];
      };
    };
  };
  /** Publiserer utkastet med gitt id. */
  publiserUtkast: {
    parameters: {
      path: {
        /** ID-en til utkastet man vil publisere */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: unknown;
      /** Bad request. Check the request body and path */
      400: {
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** Conflict */
      409: {
        content: {
          "application/json": components["schemas"]["ConflictResponse"][];
        };
      };
    };
  };
  /** Henter stemmekrets med gitt id */
  hentStemmekrets: {
    parameters: {
      path: {
        /** ID-en til stemmekretsen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["StemmekretsResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["StemmekretsResponse"];
        };
      };
    };
  };
  /** Henter historiske revisjoner til en stemmekrets med gitt id */
  hentStemmekretsRevisjoner: {
    parameters: {
      path: {
        /** ID-en til stemmekretsen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["RevisjonRef"][];
        };
      };
    };
  };
  /** Henter en gitt historisk revisjon av en stemmekrets */
  hentStemmekretsRevisjon: {
    parameters: {
      path: {
        /** ID-en til stemmekrets man vil hente */
        id: string;
        /** ID til revisjonen man vil hente */
        revisjon: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["StemmekretsResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["StemmekretsResponse"];
        };
      };
    };
  };
  /** Henter grensene til en stemmekrets med gitt id */
  hentGrenserForStemmekrets: {
    parameters: {
      path: {
        /** ID-en til stemmekretsen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  /** Henter alle nasjoner i Nasjonal inndelingsbase. */
  hentNasjoner: {
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["NasjonRef"][];
        };
      };
    };
  };
  /** Henter nasjon med gitt id */
  hentNasjon: {
    parameters: {
      path: {
        /** ID-en til nasjonen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["NasjonRef"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["NasjonResponse"];
        };
      };
    };
  };
  /** Henter historiske revisjoner til en nasjon med gitt id */
  hentNasjonRevisjoner: {
    parameters: {
      path: {
        /** ID-en til nasjonen man vil hente historiske revisjoner for */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["RevisjonRef"][];
        };
      };
    };
  };
  /** Henter en gitt historisk revisjon av en nasjon */
  hentNasjonRevisjon: {
    parameters: {
      path: {
        /** Id til nasjonen man vil hente */
        id: string;
        /** Id til revisjonen man vil hente */
        revisjon: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["NasjonResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["NasjonResponse"];
        };
      };
    };
  };
  /** Henter grensene til en nasjon med gitt id */
  hentGrenserForNasjon: {
    parameters: {
      path: {
        /** ID-en til nasjonen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  /** Henter alle kommuner i Nasjonal inndelingsbase. */
  hentKommuner: {
    parameters: {
      query: {
        /** Valgfri id til et fylke for å filtrere kommuner innenfor et fylke */
        fylkeid?: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["KommuneRef"][];
        };
      };
    };
  };
  /** Henter kommune med gitt id */
  hentKommune: {
    parameters: {
      path: {
        /** ID-en til kommunen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["KommuneResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["KommuneResponse"];
        };
      };
    };
  };
  hentKommunesStemmekretser: {
    parameters: {
      path: {
        /** ID til kommunen man vil hente stemmekretsene til */
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["StemmekretsRef"][];
        };
      };
    };
  };
  /** Henter historiske revisjoner til en kommune med gitt id */
  hentKommuneRevisjoner: {
    parameters: {
      path: {
        /** ID-en til kommunen man vil hente historiske revisjoner for */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["RevisjonRef"][];
        };
      };
    };
  };
  /** Henter en gitt historisk revisjon av en kommune */
  hentKommuneRevisjon: {
    parameters: {
      path: {
        /** ID-en til kommunen man vil hente */
        id: string;
        /** ID til revisjonen man vil hente */
        revisjon: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["KommuneResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["KommuneResponse"];
        };
      };
    };
  };
  /** Henter alle grunnkretser som tilhører en kommune. */
  hentKommunesGrunnkretser: {
    parameters: {
      path: {
        /** ID til kommunen man vil hente grunnkretsene til */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["GrunnkretsRef"][];
        };
      };
    };
  };
  /** Henter grensene til en kommune med gitt id */
  hentGrenserForKommune: {
    parameters: {
      path: {
        /** ID-en til kommunen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  fetchTerrengdetaljkoder: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["KodelisteRespons"];
        };
      };
    };
  };
  fetchNoeyaktighetsklasser: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["KodelisteRespons"];
        };
      };
    };
  };
  fetchMaalemetodeKoder: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["KodelisteRespons"];
        };
      };
    };
  };
  fetchLandkoder: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["KodelisteRespons"];
        };
      };
    };
  };
  fetchKommunenumre: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["KodelisteRespons"];
        };
      };
    };
  };
  fetchGrensetyper: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["KodelisteRespons"];
        };
      };
    };
  };
  fetchGrensestatuskoder: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["KodelisteRespons"];
        };
      };
    };
  };
  fetchFylkesnumre: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["KodelisteRespons"];
        };
      };
    };
  };
  fetchFastsettingstyper: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["KodelisteRespons"];
        };
      };
    };
  };
  /** Henter grunnkrets med gitt id */
  hentGrunnkrets: {
    parameters: {
      path: {
        /** ID-en til grunnkretsen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["GrunnkretsResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["GrunnkretsResponse"];
        };
      };
    };
  };
  /** Henter historiske revisjoner til en grunnkrets med gitt id */
  hentGrunnkretsRevisjoner: {
    parameters: {
      path: {
        /** ID-en til grunnkretsen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["RevisjonRef"][];
        };
      };
    };
  };
  /** Henter en gitt historisk revisjon av en grunnkrets */
  hentGrunnkretsRevisjon: {
    parameters: {
      path: {
        /** ID-en til grunnkretsen man vil hente */
        id: string;
        /** ID til revisjonen man vil hente */
        revisjon: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["GrunnkretsResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["GrunnkretsResponse"];
        };
      };
    };
  };
  /** Henter grensene til en grunnkrets med gitt id */
  hentGrenserForGrunnkrets: {
    parameters: {
      path: {
        /** ID-en til grunnkretsen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  /** Henter grense med gitt id */
  hentGrense: {
    parameters: {
      path: {
        /** ID-en til grensen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Feature"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["Feature"];
        };
      };
    };
  };
  /** Henter historiske revisjoner for grense med gitt id */
  hentGrenseRevisjoner: {
    parameters: {
      path: {
        /** ID-en til grensen man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["RevisjonRef"][];
        };
      };
    };
  };
  /** Henter gitt historisk revisjon for gitt grense */
  hentGrenseRevisjon: {
    parameters: {
      path: {
        /** ID til grensen man vil hente */
        id: string;
        /** ID til revisjonen man vil hente */
        revisjon: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Feature"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["Feature"];
        };
      };
    };
  };
  /** Henter alle fylker i Nasjonal inndelingsbase. */
  hentFylker: {
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FylkeRef"][];
        };
      };
    };
  };
  /** Henter fylke med gitt id */
  hentFylke: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FylkeRef"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FylkeResponse"];
        };
      };
    };
  };
  /** Henter historiske revisjoner til et fylke med gitt id */
  hentFylkesRevisjoner: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente historiske revisjoner for */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["RevisjonRef"][];
        };
      };
    };
  };
  /** Henter en gitt historisk revisjon av et fylke */
  hentFylkesRevisjon: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
        /** ID til revisjonen man vil hente */
        revisjon: number;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FylkeResponse"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FylkeResponse"];
        };
      };
    };
  };
  /** Henter grensene til et fylke med gitt id */
  hentGrenserForFylke: {
    parameters: {
      path: {
        /** ID-en til fylket man vil hente */
        id: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["FeatureCollection"];
        };
      };
    };
  };
  /** Henter stemmekretser med gitte id-er */
  hentStemmekretserForIds: {
    parameters: {
      query: {
        /** ID-ene til stemmekretsene man vil hente */
        id: string[];
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["StemmekretsResponse"][];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["StemmekretsResponse"][];
        };
      };
    };
  };
  /** Henter alle stemmekretser for gitt kommunenummer */
  hentAlleStemmekretserForKommune: {
    parameters: {
      path: {
        /** Kommunenummer for kommune man ønsker å hente stemmekretsene til */
        kommunenummer: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["StemmekretsResponse"][];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["StemmekretsResponse"][];
        };
      };
    };
  };
  /** Henter alle grunnkretser for gitt kommunenummer */
  hentAlleGrunnkretserForKommune: {
    parameters: {
      path: {
        /** Kommunenummer for kommune man ønsker å hente grunnkretsene til */
        kommunenummer: string;
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["GrunnkretsResponse"][];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["GrunnkretsResponse"][];
        };
      };
    };
  };
  /** Henter grunnkretser med gitte id-er */
  hentGrunnkretserForIds: {
    parameters: {
      query: {
        /** ID-ene til grunnkretsene man vil hente */
        id: string[];
      };
    };
    responses: {
      /** Successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["GrunnkretsResponse"][];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["GrunnkretsResponse"][];
        };
      };
    };
  };
}

export interface external {}
