apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: baat-geonorge-no
  namespace: nibas
spec:
  hosts:
    - baat.geonorge.no
  gateways:
    - istio-system/istio-egressgateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: target-egress-gateway
        port:
          number: 443
  tls:
  - match:
      - port: 443
        sniHosts:
          - baat.geonorge.no
        gateways:
          - mesh
    route:
      - destination:
          host: baat.geonorge.no
          port:
            number: 443
