name: Cleanup old images
on:
  workflow_dispatch:
  schedule:
    - cron: "00 1 * * 1" # 01:00 on Mondays.

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-name: "nibas-frontend"
          package-type: "container"
          min-versions-to-keep: 20
