name: cleanup-github-container-images
on:
  workflow_dispatch:
  schedule:
    - cron: '00 1 * * 1'  # 01:00 on Mondays.

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'nibas-frontend'
          package-type: 'container'
          min-versions-to-keep: 20
