name: Deploy branch to dev
on: workflow_dispatch

env:
    image_name: nibas-frontend
    registry: ghcr.io
    registry_path: kartverket

jobs:
    build:
        permissions:
            contents: write
            packages: write
            security-events: write
            actions: read
        uses: kartverket/nibas-frontend/.github/workflows/build-app.yml@main
        with:
            deploy_ghcr: true
        secrets: inherit

    deploy-argo:
        needs: build
        uses: kartverket/smia-apps/.github/workflows/release-app.yml@main
        with:
            application: nibas-frontend
            version: ${{ needs.build.outputs.version }}
            digest: ${{ needs.build.outputs.digest }}
            deploy_dev: true
        secrets:
            PAT_TOKEN: ${{ secrets.PAT_ARGOCD }}
