name: nibas-frontend-feature-branches
on:
  push:
    branches-ignore: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: echo //npm.pkg.github.com/:_authToken=${{secrets.PAT_READ_PACKAGE}} >> .npmrc
      - run: cat .npmrc
      - run: npm ci --no-audit
      - run: npm audit --production
      - run: npm run build --if-present
      - run: npm test