name: Promote test to prod
on: workflow_dispatch

jobs:
  deploy-argo:
    permissions:
      id-token: write
    uses: kartverket/smia-apps/.github/workflows/promote-app-octo-sts.yml@main
    with:
      application: nibas-frontend
      identity: nibas
