name: Release PR
on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: "Will be 'nibas-{branch-name}' in the environment. Must be a valid hostname label. If not provided, the current branch's name will be used."
        required: false
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
    branches:
      - main

concurrency:
  group: feature-env-${{ github.head_ref }}
  cancel-in-progress: true

env:
  image_name: nibas-frontend
  registry: ghcr.io
  registry_path: kartverket

jobs:
  should-create-feature-env:
    if: ${{ github.event_name == 'pull_request' }}
    uses: kartverket/nibas-frontend/.github/workflows/check-changes.yml@main
    with:
      ignore-paths: "README.md,.github/,.vscode/,.security/"

  determine-branch-name-pr:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false && needs.should-create-feature-env.outputs.has-relevant-changes == 'true' }}
    needs: should-create-feature-env
    name: Determine Branch Name (PR)
    runs-on: ubuntu-latest
    outputs:
      BRANCH_NAME: ${{ steps.determine-branch.outputs.branch_name_output }}
    steps:
      - name: Determine branch name
        id: determine-branch
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]')
          echo "branch_name_output=$BRANCH_NAME" >> $GITHUB_OUTPUT

  determine-branch-name-manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Determine Branch Name (Manual)
    runs-on: ubuntu-latest
    outputs:
      BRANCH_NAME: ${{ steps.determine-branch.outputs.branch_name_output }}
    steps:
      - name: Determine branch name
        id: determine-branch
        run: |
          if [ "${{ inputs.branch-name }}" != "" ]; then
            BRANCH_NAME="${{ inputs.branch-name }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi
          BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]')
          echo "branch_name_output=$BRANCH_NAME" >> $GITHUB_OUTPUT

  validate-branch-name-pr:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false && needs.should-create-feature-env.outputs.has-relevant-changes == 'true' }}
    needs: [should-create-feature-env, determine-branch-name-pr]
    runs-on: ubuntu-latest
    name: Validate branch-name input (PR)
    outputs:
      valid: ${{ steps.validate.outputs.valid }}
    steps:
      - name: Validate branch-name is valid hostname label
        id: validate
        run: |
          DETERMINED_BRANCH_NAME="${{ needs.determine-branch-name-pr.outputs.BRANCH_NAME }}"
          if [[ ! "$DETERMINED_BRANCH_NAME" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?$ ]]; then
            echo "Branchname is invalid as hostname label: $DETERMINED_BRANCH_NAME"
            echo "valid=false" >> $GITHUB_OUTPUT
          else
            echo "Branchname is valid as hostname label: $DETERMINED_BRANCH_NAME"
            echo "valid=true" >> $GITHUB_OUTPUT
          fi

  validate-branch-name-manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: determine-branch-name-manual
    runs-on: ubuntu-latest
    name: Validate branch-name input (Manual)
    outputs:
      valid: ${{ steps.validate.outputs.valid }}
    steps:
      - name: Validate branch-name is valid hostname label
        id: validate
        run: |
          DETERMINED_BRANCH_NAME="${{ needs.determine-branch-name-manual.outputs.BRANCH_NAME }}"
          if [[ ! "$DETERMINED_BRANCH_NAME" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?$ ]]; then
            echo "Branchname is invalid as hostname label: $DETERMINED_BRANCH_NAME"
            echo "valid=false" >> $GITHUB_OUTPUT
          else
            echo "Branchname is valid as hostname label: $DETERMINED_BRANCH_NAME"
            echo "valid=true" >> $GITHUB_OUTPUT
          fi

  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false }}
    permissions:
      contents: write
      packages: write
      security-events: write
      actions: read
    uses: kartverket/nibas-frontend/.github/workflows/build-app.yml@main
    with:
      deploy_ghcr: true
    secrets: inherit

  pharos:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false }}
    needs: [build]
    name: Run Pharos security scan
    permissions:
      actions: read
      packages: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: "Run Pharos"
        uses: kartverket/pharos@v0.5.0
        with:
          allow_severity_level: critical
          image_url: ${{ needs.build.outputs.image_url }}

  deploy-pull-request-pr:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false && needs.should-create-feature-env.outputs.has-relevant-changes == 'true' && needs.validate-branch-name-pr.outputs.valid == 'true' }}
    needs:
      [
        should-create-feature-env,
        validate-branch-name-pr,
        determine-branch-name-pr,
        build,
        pharos,
      ]
    name: Deploy Pull Request (PR)
    permissions:
      id-token: write
      contents: read
    uses: kartverket/smia-apps/.github/workflows/release-feature-branch.yml@main
    secrets:
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
    with:
      branch-name: ${{ needs.determine-branch-name-pr.outputs.BRANCH_NAME }}
      application: nibas-frontend
      version: ${{ needs.build.outputs.version }}
      digest: ${{ needs.build.outputs.digest }}
      identity: nibas

  deploy-pull-request-manual:
    if: ${{ github.event_name == 'workflow_dispatch' && needs.validate-branch-name-manual.outputs.valid == 'true' }}
    needs:
      [validate-branch-name-manual, determine-branch-name-manual, build, pharos]
    name: Deploy Pull Request (Manual)
    permissions:
      id-token: write
      contents: read
    uses: kartverket/smia-apps/.github/workflows/release-feature-branch.yml@main
    secrets:
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
    with:
      branch-name: ${{ needs.determine-branch-name-manual.outputs.BRANCH_NAME }}
      application: nibas-frontend
      version: ${{ needs.build.outputs.version }}
      digest: ${{ needs.build.outputs.digest }}
      identity: nibas

  deploy-status-pr:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false && needs.should-create-feature-env.outputs.has-relevant-changes == 'true' && needs.validate-branch-name-pr.outputs.valid == 'true' }}
    needs: [deploy-pull-request-pr, determine-branch-name-pr]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Create GitHub Deployment
        id: create_deployment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
              environment: `nibas-${{ needs.determine-branch-name-pr.outputs.BRANCH_NAME }}`,
              transient_environment: true,
              auto_merge: false,
              required_contexts: [],
              description: "PR preview environment",
            });

            core.setOutput("deployment_id", result.data.id);

      - name: Mark Deployment Successful
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.create_deployment.outputs.deployment_id }},
              state: "success",
              environment_url: "https://nibas-${{ needs.determine-branch-name-pr.outputs.BRANCH_NAME }}.atkv3-dev.kartverket-intern.cloud",
            });
