name: nibas-frontend
on:
  push:
    branches: master

permissions:
  id-token: write
  contents: 'read'

env:
  image_name: nibas-frontend
  registry: ghcr.io
  registry_path: kartverket

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - name: Update npmrc with secret to install internal packages
        run: |
          cp .npmrc .npmrc-copy
          echo //npm.pkg.github.com/:_authToken=${{secrets.PAT_SCOPE_READ_PACKAGE}} >> .npmrc

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ github.token }}

      - name: Build and test
        run: |
          npm ci --no-audit
          npm audit --production
          npm run build --if-present
          npm test
        env:
          REACT_APP_VERSION: ${{ steps.tag_version.outputs.new_version }}

      - name: Remove npmrc with secret
        run: |
          rm .npmrc
          mv .npmrc-copy .npmrc

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build docker and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.registry }}/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }},${{ env.registry }}/${{ github.repository }}:latest

  deploy-dev:
    needs: build
    permissions:
      id-token: write
      pull-requests: write
      contents: read
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@v3.0.1
    with:
      runner: atkv1-dev
      environment: dev
      kubernetes_cluster: atkv1-dev
      terraform_workspace: dev
      terraform_options: -var-file=variables/dev.tfvars -var=NIBAS_FRONTEND_VERSION=${{ needs.build.outputs.new_tag }}
      terraform_backend_config: -backend-config=backend/dev.gcs.tfbackend
      working_directory: terraform
      workload_identity_provider: projects/747318126147/locations/global/workloadIdentityPools/nibas-deploy-pool/providers/github-provider
      service_account: nibas-deploy@nibas-dev-075c.iam.gserviceaccount.com
      vault_role: nibas-frontend-read-role
      project_id: kubernetes-dev-94b9
      deploy_on: 'refs/heads/master'

  deploy-test:
    needs: build
    permissions:
      id-token: write
      pull-requests: write
      contents: read
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@v3.0.1
    with:
      runner: atkv1-test
      environment: test
      kubernetes_cluster: atkv1-test
      terraform_workspace: test
      terraform_options: -var-file=variables/test.tfvars -var=NIBAS_FRONTEND_VERSION=${{ needs.build.outputs.new_tag }}
      terraform_backend_config: -backend-config=backend/test.gcs.tfbackend
      working_directory: terraform
      workload_identity_provider: projects/935702487708/locations/global/workloadIdentityPools/nibas-deploy-pool/providers/github-provider
      service_account: nibas-deploy@nibas-test-36cb.iam.gserviceaccount.com
      vault_role: nibas-frontend-read-role
      project_id: kubernetes-test-94f6
      deploy_on: 'refs/heads/master'