name: Release PR
on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: "Name of the branch to create feature-branch for"
        required: true
  pull_request:
    branches:
      - main

env:
  image_name: nibas-frontend
  registry: ghcr.io
  registry_path: kartverket

jobs:
  build:
    permissions:
      contents: write
      packages: write
      security-events: write
      actions: read
    uses: kartverket/nibas-frontend/.github/workflows/build-app.yml@main
    with:
      deploy_ghcr: true
    secrets: inherit

  test:
    permissions:
      contents: write
      actions: read
    uses: kartverket/nibas-frontend/.github/workflows/test-app.yml@main
    secrets: inherit

  pharos:
    name: Run Pharos security scan
    needs: build
    permissions:
      actions: read
      packages: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: "Run Pharos"
        uses: kartverket/pharos@v0.3.1
        with:
          allow_severity_level: critical
          image_url: ${{ needs.build.outputs.image_url }}

  deploy-pull-request:
    permissions:
      id-token: write
    needs: [build, test, pharos]
    runs-on: ubuntu-latest
    steps:
      - name: Determine branch name
        id: determine-branch
        run: |
          if [ "${{ inputs.branch-name }}" != "" ]; then
            echo "branch_name=${{ inputs.branch-name }}" >> $GITHUB_ENV
          else
            echo "branch_name=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi

      - name: Deploy Pull Request
        uses: kartverket/smia-apps/.github/workflows/release-feature-branch.yml@main
        with:
          branch-name: ${{ env.branch_name }}
          application: nibas-frontend
          version: ${{ needs.build.outputs.version }}
          digest: ${{ needs.build.outputs.digest }}
          identity: nibas
