name: Cypress Tests with Dependency and Artifact Caching

on:
  pull_request:
    branches: [main]
  merge_group:

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kartverket'

      - name: Update npmrc with secret to install internal packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PAT_SCOPE_READ_PACKAGE }}" > .npmrc
          
      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: build

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
