name: Takedown PR
on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: "Name of the feature environment to be deleted."
        required: true
  pull_request:
    types:
      - closed

jobs:
  determine-branch-name:
    name: Determine Branch Name
    runs-on: ubuntu-latest
    outputs:
      BRANCH_NAME: ${{ steps.determine-branch.outputs.branch_name_output }}
    steps:
      - name: Determine branch name
        id: determine-branch
        run: |
          if [ "${{ inputs.branch-name }}" != "" ]; then
            BRANCH_NAME="${{ inputs.branch-name }}"
          else
            BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          fi
          BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]')
          echo "branch_name_output=$BRANCH_NAME" >> $GITHUB_OUTPUT

  takedown-pull-request:
    needs: [determine-branch-name]
    permissions:
      id-token: write
      contents: read
    uses: kartverket/smia-apps/.github/workflows/delete-feature-branch.yml@main
    secrets:
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
    with:
      branch-name: ${{ needs.determine-branch-name.outputs.BRANCH_NAME }}
      identity: nibas

  deactivate-deployment:
    needs: [takedown-pull-request]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    steps:
      - uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ref = '${{ needs.determine-branch-name.outputs.BRANCH_NAME }}';
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const { data } = await github.rest.repos.listDeployments({
              owner,
              repo,
              ref
            });

            if (data.length === 0) {
              console.log("No deployments found for this PR.");
              return;
            }

            await github.rest.repos.deleteDeployment({
              owner,
              repo,
              deployment_id: data[0].id,
            });
