name: Takedown PR
on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: "Name of the feature environment to be deleted."
        required: true
  pull_request:
    types:
      - closed

jobs:
  determine-branch-name:
    name: Determine Branch Name
    runs-on: ubuntu-latest
    outputs:
      BRANCH_NAME: ${{ steps.determine-branch.outputs.branch_name_output }}
    steps:
      - name: Determine branch name
        id: determine-branch
        run: |
          if [ "${{ inputs.branch-name }}" != "" ]; then
            echo "branch_name_output=${{ inputs.branch-name }}" >> $GITHUB_OUTPUT
          else
            echo "branch_name_output=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          fi

  takedown-pull-request:
    needs: [determine-branch-name]
    permissions:
      id-token: write
    uses: kartverket/smia-apps/.github/workflows/delete-feature-branch.yml@main
    with:
      branch-name: ${{ needs.determine-branch-name.outputs.BRANCH_NAME }}
      identity: nibas
